// property_provider.dart
import 'package:flutter/material.dart';
import 'package:leez/frontend/models/property.dart';
import 'package:cached_network_image/cached_network_image.dart';

class PropertyProvider extends ChangeNotifier {
  // Store your dummy data here:
  final List<Property> _allProperties = [
    Property(
      id: 'car1',
      title: 'Maruti Suzuki Ertiga',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 1452,
      totalPrice: 2500,
      images: [
        'https://zoomcar-assets.zoomcar.com/902303/HostCarImage/mini_magick20250103-1-1hxc60b757c1ff3-2bd4-422d-a324-243cf95fb844.jpeg',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),

    Property(
      id: 'car2',
      title: 'Maruti Suzuki Celerio',
      location: 'Hyderabad, India',
      rating: 4.3,
      price: 914,
      totalPrice: 2500,
      images: [
        'https://zoomcar-assets.zoomcar.com/829273/HostCarImage/mini_magick20241205-3999-8qbm0a092dd9b9-3ce7-4dc0-b432-eed833201ec6.jpeg',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),

    Property(
      id: 'car3',
      title: 'Toyota Glanza ',
      location: 'Delhi, India',
      rating: 4.8,
      price: 1202,
      totalPrice: 3500,
      images: [
        'https://zoomcar-assets.zoomcar.com/734855/HostCarImage/mini_magick20241205-3999-1az1rqf505eaa7a-9b78-407f-abb9-41f62d7ff0e2.jpeg',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'car4',
      title: 'Hyundai Exter ',
      location: 'Bangalore, India',
      rating: 4.6,
      price: 1276,
      totalPrice: 3000,
      images: [
        'https://zoomcar-assets.zoomcar.com/743537/HostCarImage/mini_magick20241205-3999-mo60m8d791a37e-f668-4534-bd7d-d70a40cf2042.jpeg',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '20 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'car5',
      title: 'Maruti Suzuki Ertiga',
      location: 'Hyderabad, India',
      rating: 4.2,
      price: 1800,
      totalPrice: 2200,
      images: [
        'https://zoomcar-assets.zoomcar.com/962997/HostCarImage/RackMultipart20250228-45-1f88e5fd51df74d-dfe9-4fea-85d3-50cc73c21d5a.jpg',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car6',
      title: 'KIA Seltos ',
      location: 'Chennai, India',
      rating: 4.7,
      price: 2800,
      totalPrice: 3300,
      images: [
        'https://zoomcar-assets.zoomcar.com/837305/HostCarImage/mini_magick20241204-1-vf2agf35bf683-3206-42bb-91de-a95e7d0fdfaa.jpeg',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available this weekend',
    ),
    Property(
      id: 'car7',
      title: 'Vintage Classic',
      location: 'Kolkata, India',
      rating: 4.4,
      price: 2200,
      totalPrice: 2700,
      images: ['assets/car2.png'],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available soon',
    ),

    // Bikes (6 items)
    Property(
      id: 'bike1',
      title: 'Sports Bike',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 1500,
      totalPrice: 1800,
      images: ['assets/bike.jpg'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike2',
      title: 'Cruiser Bike',
      location: 'Delhi, India',
      rating: 4.7,
      price: 1600,
      totalPrice: 1900,
      images: ['assets/bike.jpg'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'bike3',
      title: 'Electric Bike',
      location: 'Bangalore, India',
      rating: 4.8,
      price: 1700,
      totalPrice: 2000,
      images: ['assets/bike.jpg'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'bike4',
      title: 'Classic Bike',
      location: 'Hyderabad, India',
      rating: 4.3,
      price: 1400,
      totalPrice: 1700,
      images: ['assets/bike.jpg'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '6 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike5',
      title: 'Adventure Bike',
      location: 'Chennai, India',
      rating: 4.6,
      price: 1550,
      totalPrice: 1850,
      images: ['assets/bike.jpg'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '9 km away',
      availabilityDescription: 'Available this weekend',
    ),
    Property(
      id: 'bike6',
      title: 'Touring Bike',
      location: 'Kolkata, India',
      rating: 4.4,
      price: 1500,
      totalPrice: 1800,
      images: ['assets/bike.jpg'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '11 km away',
      availabilityDescription: 'Available soon',
    ),

    // Laptops (6 items)
    Property(
      id: 'laptop1',
      title: 'Gaming Laptop',
      location: 'Mumbai, India',
      rating: 4.9,
      price: 80000,
      totalPrice: 85000,
      images: ['assets/laptop1.png'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'In stock',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'laptop2',
      title: 'Ultrabook',
      location: 'Delhi, India',
      rating: 4.8,
      price: 75000,
      totalPrice: 80000,
      images: ['assets/laptop.png'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'In stock',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'laptop3',
      title: 'Business Laptop',
      location: 'Bangalore, India',
      rating: 4.7,
      price: 70000,
      totalPrice: 75000,
      images: ['assets/laptop1.png'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'In stock',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'laptop4',
      title: 'Convertible Laptop',
      location: 'Hyderabad, India',
      rating: 4.6,
      price: 68000,
      totalPrice: 73000,
      images: ['assets/laptop.png'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'In stock',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'laptop5',
      title: '2-in-1 Laptop',
      location: 'Chennai, India',
      rating: 4.8,
      price: 72000,
      totalPrice: 77000,
      images: ['assets/laptop1.png'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'In stock',
      availabilityDescription: 'Available this weekend',
    ),
    Property(
      id: 'laptop6',
      title: 'Budget Laptop',
      location: 'Kolkata, India',
      rating: 4.5,
      price: 60000,
      totalPrice: 65000,
      images: ['assets/laptop.png'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'In stock',
      availabilityDescription: 'Available soon',
    ),

    // Cameras (6 items)
    Property(
      id: 'camera1',
      title: 'DSLR Camera',
      location: 'Mumbai, India',
      rating: 4.9,
      price: 45000,
      totalPrice: 48000,
      images: ['assets/cam1.png'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'In store',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera2',
      title: 'Mirrorless Camera',
      location: 'Delhi, India',
      rating: 4.8,
      price: 50000,
      totalPrice: 53000,
      images: ['assets/cam3.png'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'In store',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'camera3',
      title: 'Compact Camera',
      location: 'Bangalore, India',
      rating: 4.7,
      price: 35000,
      totalPrice: 38000,
      images: ['assets/cam4.png'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'In store',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'camera4',
      title: 'Action Camera',
      location: 'Hyderabad, India',
      rating: 4.6,
      price: 30000,
      totalPrice: 33000,
      images: ['assets/cam78.png'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'In store',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera5',
      title: 'Film Camera',
      location: 'Chennai, India',
      rating: 4.5,
      price: 28000,
      totalPrice: 31000,
      images: ['assets/cam1.png'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'In store',
      availabilityDescription: 'Available this weekend',
    ),
    Property(
      id: 'camera6',
      title: 'Point & Shoot',
      location: 'Kolkata, India',
      rating: 4.4,
      price: 22000,
      totalPrice: 25000,
      images: ['assets/cam3.png'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'In store',
      availabilityDescription: 'Available soon',
    ),

    // Houses (6 items)
    Property(
      id: 'house1',
      title: 'Modern Farm House',
      location: 'Coimbatore, India',
      rating: 4.9,
      price: 1836,
      totalPrice: 2500,
      images: ['assets/nat1.png'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '259 km away',
      availabilityDescription: '5-9 Apr',
    ),
    Property(
      id: 'house2',
      title: 'Beachfront Villa',
      location: 'Goa, India',
      rating: 4.8,
      price: 2549,
      totalPrice: 3200,
      images: ['assets/nat2.png'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '200 km away',
      availabilityDescription: '10-15 Apr',
    ),
    Property(
      id: 'house3',
      title: 'Mountain Cabin',
      location: 'Himalayas, India',
      rating: 4.7,
      price: 1899,
      totalPrice: 2600,
      images: ['assets/nat2.png'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '300 km away',
      availabilityDescription: '15-20 Apr',
    ),
    Property(
      id: 'house4',
      title: 'Luxury Apartment',
      location: 'Mumbai, India',
      rating: 4.9,
      price: 3249,
      totalPrice: 4000,
      images: ['assets/nat3.png'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house5',
      title: 'Urban Condo',
      location: 'Bangalore, India',
      rating: 4.6,
      price: 2900,
      totalPrice: 3500,
      images: ['assets/nat4.png'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '3 km away',
      availabilityDescription: 'Available today',
    ),
    // Cars (6 items)
    Property(
      id: 'car1',
      title: 'Sporty Car',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 2000,
      totalPrice: 2500,
      images: ['assets/car1.png'],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car2',
      title: 'Luxury Sedan',
      location: 'Delhi, India',
      rating: 4.3,
      price: 3000,
      totalPrice: 3500,
      images: ['assets/car2.png'],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car3',
      title: 'Compact Hatchback',
      location: 'Bangalore, India',
      rating: 4.0,
      price: 1800,
      totalPrice: 2200,
      images: ['assets/car3.png'],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car4',
      title: 'Convertible',
      location: 'Hyderabad, India',
      rating: 4.8,
      price: 4000,
      totalPrice: 4500,
      images: ['assets/car4.jpg'],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car5',
      title: 'SUV',
      location: 'Chennai, India',
      rating: 4.2,
      price: 3500,
      totalPrice: 4000,
      images: ['assets/car5.png'],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '20 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car6',
      title: 'Electric Car',
      location: 'Kolkata, India',
      rating: 4.7,
      price: 3200,
      totalPrice: 3700,
      images: ['assets/car6.png'],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available now',
    ),

    // Bikes (6 items)
    Property(
      id: 'bike1',
      title: 'Sport Bike',
      location: 'Mumbai, India',
      rating: 4.3,
      price: 800,
      totalPrice: 950,
      images: ['assets/bikes/bike1.png'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '3 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike2',
      title: 'Cruiser Bike',
      location: 'Delhi, India',
      rating: 4.1,
      price: 700,
      totalPrice: 850,
      images: ['assets/bikes/bike2.png'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike3',
      title: 'Electric Bike',
      location: 'Bangalore, India',
      rating: 4.5,
      price: 900,
      totalPrice: 1050,
      images: ['assets/bikes/bike3.png'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '4 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike4',
      title: 'Off-Road Bike',
      location: 'Hyderabad, India',
      rating: 4.4,
      price: 750,
      totalPrice: 900,
      images: ['assets/bikes/bike4.png'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '6 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike5',
      title: 'Classic Bike',
      location: 'Chennai, India',
      rating: 4.0,
      price: 650,
      totalPrice: 800,
      images: ['assets/bikes/bike5.png'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike6',
      title: 'Adventure Bike',
      location: 'Kolkata, India',
      rating: 4.6,
      price: 950,
      totalPrice: 1100,
      images: ['assets/bikes/bike6.png'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available now',
    ),

    // Laptops (6 items)
    Property(
      id: 'laptop1',
      title: 'Gaming Laptop',
      location: 'Mumbai, India',
      rating: 4.7,
      price: 50000,
      totalPrice: 52000,
      images: ['assets/laptops/laptop1.png'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'laptop2',
      title: 'Ultrabook',
      location: 'Delhi, India',
      rating: 4.5,
      price: 60000,
      totalPrice: 63000,
      images: ['assets/laptops/laptop2.png'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'laptop3',
      title: 'Business Laptop',
      location: 'Bangalore, India',
      rating: 4.3,
      price: 55000,
      totalPrice: 57000,
      images: ['assets/laptops/laptop3.png'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'laptop4',
      title: 'Convertible Laptop',
      location: 'Hyderabad, India',
      rating: 4.6,
      price: 65000,
      totalPrice: 68000,
      images: ['assets/laptops/laptop4.png'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'laptop5',
      title: 'Budget Laptop',
      location: 'Chennai, India',
      rating: 4.0,
      price: 40000,
      totalPrice: 42000,
      images: ['assets/laptops/laptop5.png'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'laptop6',
      title: 'High-Performance Laptop',
      location: 'Kolkata, India',
      rating: 4.8,
      price: 70000,
      totalPrice: 73000,
      images: ['assets/laptops/laptop6.png'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),

    // Cameras (6 items)
    Property(
      id: 'camera1',
      title: 'DSLR Camera',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 25000,
      totalPrice: 27000,
      images: ['assets/cameras/camera1.png'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Store Pickup',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera2',
      title: 'Mirrorless Camera',
      location: 'Delhi, India',
      rating: 4.7,
      price: 30000,
      totalPrice: 32000,
      images: ['assets/cameras/camera2.png'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Store Pickup',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera3',
      title: 'Point & Shoot',
      location: 'Bangalore, India',
      rating: 4.2,
      price: 15000,
      totalPrice: 16500,
      images: ['assets/cameras/camera3.png'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Store Pickup',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera4',
      title: 'Action Camera',
      location: 'Hyderabad, India',
      rating: 4.4,
      price: 18000,
      totalPrice: 19500,
      images: ['assets/cameras/camera4.png'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Store Pickup',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera5',
      title: 'Film Camera',
      location: 'Chennai, India',
      rating: 4.0,
      price: 12000,
      totalPrice: 13500,
      images: ['assets/cameras/camera5.png'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Store Pickup',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera6',
      title: 'Professional Camera',
      location: 'Kolkata, India',
      rating: 4.8,
      price: 35000,
      totalPrice: 37000,
      images: ['assets/cameras/camera6.png'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Store Pickup',
      availabilityDescription: 'Available now',
    ),

    // Houses (6 items)
    Property(
      id: 'house1',
      title: 'Luxury Villa',
      location: 'Mumbai, India',
      rating: 4.9,
      price: 150000,
      totalPrice: 160000,
      images: ['assets/houses/house1.png'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house2',
      title: 'Modern Apartment',
      location: 'Delhi, India',
      rating: 4.4,
      price: 90000,
      totalPrice: 95000,
      images: ['assets/houses/house2.png'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house3',
      title: 'Cozy Cottage',
      location: 'Bangalore, India',
      rating: 4.2,
      price: 70000,
      totalPrice: 75000,
      images: ['assets/houses/house3.png'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house4',
      title: 'Penthouse Suite',
      location: 'Hyderabad, India',
      rating: 4.8,
      price: 200000,
      totalPrice: 210000,
      images: ['assets/houses/house4.png'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '1 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house5',
      title: 'Suburban Home',
      location: 'Chennai, India',
      rating: 4.3,
      price: 80000,
      totalPrice: 85000,
      images: ['assets/houses/house5.png'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '6 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house6',
      title: 'Beachside Bungalow',
      location: 'Kolkata, India',
      rating: 4.7,
      price: 120000,
      totalPrice: 125000,
      images: ['assets/houses/house6.png'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '3 km away',
      availabilityDescription: 'Available now',
    ),

    // Mobiles (6 items)
    Property(
      id: 'mobile1',
      title: 'Smartphone X',
      location: 'Mumbai, India',
      rating: 4.6,
      price: 30000,
      totalPrice: 31000,
      images: ['assets/mobiles/mobile1.png'],
      category: 'Mobiles',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'mobile2',
      title: 'Smartphone Y',
      location: 'Delhi, India',
      rating: 4.4,
      price: 28000,
      totalPrice: 29000,
      images: ['assets/mobiles/mobile2.png'],
      category: 'Mobiles',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'mobile3',
      title: 'Budget Smartphone',
      location: 'Bangalore, India',
      rating: 4.1,
      price: 15000,
      totalPrice: 16000,
      images: ['assets/mobiles/mobile3.png'],
      category: 'Mobiles',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'mobile4',
      title: 'Flagship Smartphone',
      location: 'Hyderabad, India',
      rating: 4.8,
      price: 45000,
      totalPrice: 46000,
      images: ['assets/mobiles/mobile4.png'],
      category: 'Mobiles',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'mobile5',
      title: 'Gaming Smartphone',
      location: 'Chennai, India',
      rating: 4.5,
      price: 40000,
      totalPrice: 41000,
      images: ['assets/mobiles/mobile5.png'],
      category: 'Mobiles',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'mobile6',
      title: 'Compact Smartphone',
      location: 'Kolkata, India',
      rating: 4.3,
      price: 22000,
      totalPrice: 23000,
      images: ['assets/mobiles/mobile6.png'],
      category: 'Mobiles',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),

    // Cycles (6 items)
    Property(
      id: 'cycle1',
      title: 'Mountain Bike',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 5000,
      totalPrice: 5200,
      images: ['assets/cycles/cycle1.png'],
      category: 'Cycles',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'cycle2',
      title: 'Road Bike',
      location: 'Delhi, India',
      rating: 4.3,
      price: 4500,
      totalPrice: 4700,
      images: ['assets/cycles/cycle2.png'],
      category: 'Cycles',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '3 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'cycle3',
      title: 'Hybrid Bike',
      location: 'Bangalore, India',
      rating: 4.2,
      price: 4800,
      totalPrice: 5000,
      images: ['assets/cycles/cycle3.png'],
      category: 'Cycles',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '4 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'cycle4',
      title: 'Electric Cycle',
      location: 'Hyderabad, India',
      rating: 4.6,
      price: 6000,
      totalPrice: 6300,
      images: ['assets/cycles/cycle4.png'],
      category: 'Cycles',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '1 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'cycle5',
      title: 'Folding Bike',
      location: 'Chennai, India',
      rating: 4.0,
      price: 4000,
      totalPrice: 4200,
      images: ['assets/cycles/cycle5.png'],
      category: 'Cycles',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '3 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'cycle6',
      title: 'City Bike',
      location: 'Kolkata, India',
      rating: 4.4,
      price: 4300,
      totalPrice: 4500,
      images: ['assets/cycles/cycle6.png'],
      category: 'Cycles',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),

    // Clothes (6 items)
    Property(
      id: 'clothes1',
      title: 'Men\'s Jacket',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 2000,
      totalPrice: 2100,
      images: ['assets/clothes/clothes1.png'],
      category: 'Clothes',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'clothes2',
      title: 'Women\'s Dress',
      location: 'Delhi, India',
      rating: 4.7,
      price: 2500,
      totalPrice: 2600,
      images: ['assets/clothes/clothes2.png'],
      category: 'Clothes',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'clothes3',
      title: 'Casual Shirt',
      location: 'Bangalore, India',
      rating: 4.2,
      price: 1500,
      totalPrice: 1600,
      images: ['assets/clothes/clothes3.png'],
      category: 'Clothes',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'clothes4',
      title: 'Jeans',
      location: 'Hyderabad, India',
      rating: 4.4,
      price: 1800,
      totalPrice: 1900,
      images: ['assets/clothes/clothes4.png'],
      category: 'Clothes',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'clothes5',
      title: 'Sneakers',
      location: 'Chennai, India',
      rating: 4.1,
      price: 2200,
      totalPrice: 2300,
      images: ['assets/clothes/clothes5.png'],
      category: 'Clothes',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'clothes6',
      title: 'Sportswear',
      location: 'Kolkata, India',
      rating: 4.6,
      price: 2800,
      totalPrice: 2900,
      images: ['assets/clothes/clothes6.png'],
      category: 'Clothes',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),

    // Accessories (6 items)
    Property(
      id: 'accessory1',
      title: 'Wrist Watch',
      location: 'Mumbai, India',
      rating: 4.7,
      price: 3500,
      totalPrice: 3600,
      images: ['assets/accessories/accessory1.png'],
      category: 'Accessories',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'accessory2',
      title: 'Sunglasses',
      location: 'Delhi, India',
      rating: 4.4,
      price: 1500,
      totalPrice: 1600,
      images: ['assets/accessories/accessory2.png'],
      category: 'Accessories',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'accessory3',
      title: 'Leather Belt',
      location: 'Bangalore, India',
      rating: 4.3,
      price: 1200,
      totalPrice: 1300,
      images: ['assets/accessories/accessory3.png'],
      category: 'Accessories',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'accessory4',
      title: 'Handbag',
      location: 'Hyderabad, India',
      rating: 4.6,
      price: 2800,
      totalPrice: 2900,
      images: ['assets/accessories/accessory4.png'],
      category: 'Accessories',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'accessory5',
      title: 'Scarf',
      location: 'Chennai, India',
      rating: 4.1,
      price: 900,
      totalPrice: 1000,
      images: ['assets/accessories/accessory5.png'],
      category: 'Accessories',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),
    Property(
      id: 'accessory6',
      title: 'Beanie',
      location: 'Kolkata, India',
      rating: 4.5,
      price: 800,
      totalPrice: 900,
      images: ['assets/accessories/accessory6.png'],
      category: 'Accessories',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'In stock',
    ),

    // Other (6 items)
    Property(
      id: 'other1',
      title: 'Vintage Record Player',
      location: 'Mumbai, India',
      rating: 4.6,
      price: 5000,
      totalPrice: 5200,
      images: ['assets/other/other1.png'],
      category: 'Other',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'Limited stock',
    ),
    Property(
      id: 'other2',
      title: 'Antique Clock',
      location: 'Delhi, India',
      rating: 4.3,
      price: 3200,
      totalPrice: 3400,
      images: ['assets/other/other2.png'],
      category: 'Other',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'Limited stock',
    ),
    Property(
      id: 'other3',
      title: 'Handcrafted Lamp',
      location: 'Bangalore, India',
      rating: 4.4,
      price: 2700,
      totalPrice: 2900,
      images: ['assets/other/other3.png'],
      category: 'Other',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'Limited stock',
    ),
    Property(
      id: 'other4',
      title: 'Designer Vase',
      location: 'Hyderabad, India',
      rating: 4.5,
      price: 3500,
      totalPrice: 3700,
      images: ['assets/other/other4.png'],
      category: 'Other',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'Limited stock',
    ),
    Property(
      id: 'other5',
      title: 'Modern Art Sculpture',
      location: 'Chennai, India',
      rating: 4.7,
      price: 4500,
      totalPrice: 4700,
      images: ['assets/other/other5.png'],
      category: 'Other',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'Limited stock',
    ),
    Property(
      id: 'other6',
      title: 'Contemporary Wall Art',
      location: 'Kolkata, India',
      rating: 4.2,
      price: 2800,
      totalPrice: 3000,
      images: ['assets/other/other6.png'],
      category: 'Other',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Online Deal',
      availabilityDescription: 'Limited stock',
    ),
    // Cars (6 items)
    Property(
      id: 'car1',
      title: 'Sporty Car',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 2000,
      totalPrice: 2500,
      images: ['assets/car1.png'],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car2',
      title: 'Luxury Sedan',
      location: 'Delhi, India',
      rating: 4.7,
      price: 3000,
      totalPrice: 3500,
      images: ['assets/car2.png'],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'car3',
      title: 'Compact SUV',
      location: 'Bangalore, India',
      rating: 4.3,
      price: 2500,
      totalPrice: 3000,
      images: ['assets/car3.png'],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car4',
      title: 'Electric Hatchback',
      location: 'Hyderabad, India',
      rating: 4.8,
      price: 2200,
      totalPrice: 2700,
      images: ['assets/car4.jpg'],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'car5',
      title: 'Premium Coupe',
      rating: 4.6,
      location: 'Chennai, India',
      price: 4000,
      totalPrice: 4500,
      images: ['assets/car5.png'],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car6',
      title: 'Family Minivan',
      location: 'Pune, India',
      rating: 4.2,
      price: 2800,
      totalPrice: 3300,
      images: ['assets/car6.png'],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '20 km away',
      availabilityDescription: 'Available tomorrow',
    ),

    // Bikes (6 items)
    Property(
      id: 'bike1',
      title: 'Sport Bike',
      location: 'Mumbai, India',
      rating: 4.4,
      price: 800,
      totalPrice: 1000,
      images: ['https://example.com/bike1.jpg'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike2',
      title: 'Cruiser Bike',
      location: 'Delhi, India',
      rating: 4.6,
      price: 1200,
      totalPrice: 1400,
      images: ['https://example.com/bike2.jpg'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'bike3',
      title: 'Electric Scooter',
      location: 'Bangalore, India',
      rating: 4.5,
      price: 600,
      totalPrice: 800,
      images: ['https://example.com/bike3.jpg'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '3 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike4',
      title: 'Adventure Bike',
      location: 'Hyderabad, India',
      rating: 4.7,
      price: 1500,
      totalPrice: 1700,
      images: ['https://example.com/bike4.jpg'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'bike5',
      title: 'Classic Bike',
      location: 'Chennai, India',
      rating: 4.3,
      price: 1000,
      totalPrice: 1200,
      images: ['https://example.com/bike5.jpg'],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike6',
      title: 'Off-Road Bike',
      location: 'Pune, India',
      rating: 4.2,
      price: 900,
      totalPrice: 1100,
      images: ['https://example.com/bike6.jpg'],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available tomorrow',
    ),

    // Laptops (6 items)
    Property(
      id: 'laptop1',
      title: 'Gaming Laptop',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 80000,
      totalPrice: 85000,
      images: ['https://example.com/laptop1.jpg'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'laptop2',
      title: 'Ultrabook',
      location: 'Delhi, India',
      rating: 4.7,
      price: 70000,
      totalPrice: 75000,
      images: ['https://example.com/laptop2.jpg'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'laptop3',
      title: 'MacBook Pro',
      location: 'Bangalore, India',
      rating: 4.8,
      price: 120000,
      totalPrice: 125000,
      images: ['https://example.com/laptop3.jpg'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'laptop4',
      title: 'Budget Laptop',
      location: 'Hyderabad, India',
      rating: 4.2,
      price: 40000,
      totalPrice: 45000,
      images: ['https://example.com/laptop4.jpg'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'laptop5',
      title: '2-in-1 Laptop',
      location: 'Chennai, India',
      rating: 4.6,
      price: 90000,
      totalPrice: 95000,
      images: ['https://example.com/laptop5.jpg'],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'laptop6',
      title: 'Workstation Laptop',
      location: 'Pune, India',
      rating: 4.4,
      price: 100000,
      totalPrice: 105000,
      images: ['https://example.com/laptop6.jpg'],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available tomorrow',
    ),

    // Cameras (6 items)
    Property(
      id: 'camera1',
      title: 'DSLR Camera',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 50000,
      totalPrice: 55000,
      images: ['https://example.com/camera1.jpg'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera2',
      title: 'Mirrorless Camera',
      location: 'Delhi, India',
      rating: 4.7,
      price: 60000,
      totalPrice: 65000,
      images: ['https://example.com/camera2.jpg'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'camera3',
      title: 'Action Camera',
      location: 'Bangalore, India',
      rating: 4.6,
      price: 25000,
      totalPrice: 30000,
      images: ['https://example.com/camera3.jpg'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera4',
      title: 'Instant Camera',
      location: 'Hyderabad, India',
      rating: 4.3,
      price: 15000,
      totalPrice: 20000,
      images: ['https://example.com/camera4.jpg'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'camera5',
      title: 'Vlogging Camera',
      location: 'Chennai, India',
      rating: 4.8,
      price: 70000,
      totalPrice: 75000,
      images: ['https://example.com/camera5.jpg'],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera6',
      title: 'Compact Camera',
      location: 'Pune, India',
      rating: 4.2,
      price: 20000,
      totalPrice: 25000,
      images: ['https://example.com/camera6.jpg'],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available tomorrow',
    ),

    // Houses (6 items)
    Property(
      id: 'house1',
      title: 'Luxury Villa',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 20000,
      totalPrice: 25000,
      images: ['https://example.com/house1.jpg'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house2',
      title: 'Beach House',
      location: 'Goa, India',
      rating: 4.7,
      price: 30000,
      totalPrice: 35000,
      images: ['https://example.com/house2.jpg'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'house3',
      title: 'Mountain Cabin',
      location: 'Manali, India',
      rating: 4.6,
      price: 15000,
      totalPrice: 20000,
      images: ['https://example.com/house3.jpg'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house4',
      title: 'City Apartment',
      location: 'Delhi, India',
      rating: 4.3,
      price: 12000,
      totalPrice: 17000,
      images: ['https://example.com/house4.jpg'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'house5',
      title: 'Farmhouse',
      location: 'Pune, India',
      rating: 4.8,
      price: 25000,
      totalPrice: 30000,
      images: ['https://example.com/house5.jpg'],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house6',
      title: 'Studio Apartment',
      location: 'Bangalore, India',
      rating: 4.2,
      price: 10000,
      totalPrice: 15000,
      images: ['https://example.com/house6.jpg'],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available tomorrow',
    ),

    // Mobiles (6 items)
    Property(
      id: 'mobile1',
      title: 'Flagship Smartphone',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 50000,
      totalPrice: 55000,
      images: ['https://example.com/mobile1.jpg'],
      category: 'Mobiles',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'mobile2',
      title: 'Budget Smartphone',
      location: 'Delhi, India',
      rating: 4.7,
      price: 15000,
      totalPrice: 20000,
      images: ['https://example.com/mobile2.jpg'],
      category: 'Mobiles',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'mobile3',
      title: 'Gaming Phone',
      location: 'Bangalore, India',
      rating: 4.6,
      price: 40000,
      totalPrice: 45000,
      images: ['https://example.com/mobile3.jpg'],
      category: 'Mobiles',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'mobile4',
      title: 'Camera Phone',
      location: 'Hyderabad, India',
      rating: 4.3,
      price: 30000,
      totalPrice: 35000,
      images: ['https://example.com/mobile4.jpg'],
      category: 'Mobiles',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'mobile5',
      title: 'Foldable Phone',
      location: 'Chennai, India',
      rating: 4.8,
      price: 100000,
      totalPrice: 105000,
      images: ['https://example.com/mobile5.jpg'],
      category: 'Mobiles',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'mobile6',
      title: 'Mid-Range Phone',
      location: 'Pune, India',
      rating: 4.2,
      price: 20000,
      totalPrice: 25000,
      images: ['https://example.com/mobile6.jpg'],
      category: 'Mobiles',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available tomorrow',
    ),

    // Cycles (6 items)
    Property(
      id: 'cycle1',
      title: 'Mountain Bike',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 8000,
      totalPrice: 8500,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpKiIurYlrtutmCO_tZCI8ip0JQa8yfUB33g&s',
      ],
      category: 'Cycles',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '2 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'cycle2',
      title: 'Road Bike',
      location: 'Delhi, India',
      rating: 4.7,
      price: 12000,
      totalPrice: 12500,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcMoGddQtYWWUpdjgZstiDFCi79AwAVtDM1A&s',
      ],
      category: 'Cycles',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    // Cars (6 items)
    Property(
      id: 'car1',
      title: 'Sporty Car',
      location: 'Mumbai, India',
      rating: 4.5,
      price: 2000,
      totalPrice: 2500,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGWZkJbch8c4FW9dCb2Xz_REBAVZZ40e_Eig&s',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '10 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car2',
      title: 'Luxury Sedan',
      location: 'Delhi, India',
      rating: 4.7,
      price: 3000,
      totalPrice: 3500,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0kqvT08svKKnExEx5g5QAPvv1_IzG3CGzleoNJfqOjN5WgAe4cz2WTdwUxb5c7-E9wew&usqp=CAU',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available from tomorrow',
    ),
    Property(
      id: 'car3',
      title: 'Compact SUV',
      location: 'Bangalore, India',
      rating: 4.3,
      price: 2500,
      totalPrice: 3000,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKBjunDIAlGQORYUMnbNWSsg7ZmEixgx20v6jdt1rz8BX81F6BsLm68coAElxhVZymNkE&usqp=CAU',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car4',
      title: 'Electric Hatchback',
      location: 'Hyderabad, India',
      rating: 4.8,
      price: 2200,
      totalPrice: 2700,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZg532joo2kuFEbomhdXasJ53nF-sUjyLdHw&s',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available next week',
    ),

    // Cars (6 items)
    Property(
      id: 'car1',
      title: 'BMW 3 Series',
      location: 'Mumbai, Maharashtra',
      rating: 4.8,
      price: 5000,
      totalPrice: 6000,
      images: [
        'https://media.mahindrafirstchoice.com/live_web_images/usedcarsimg/mfc/405/586908/cover_image-20230922181923.jpeg',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'car2',
      title: 'Mercedes C-Class',
      location: 'Delhi, India',
      rating: 4.7,
      price: 6000,
      totalPrice: 7200,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgeTH9fLGHcIzc-SsiOO_DBtRFLEDd6HJpXXJ0mKfly0dPdQXqyNEP6ETwuAiHDthgdVs&usqp=CAU',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'car3',
      title: 'Audi A4',
      location: 'Bangalore, Karnataka',
      rating: 4.6,
      price: 5500,
      totalPrice: 6600,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxlVCa3tp50BRrNO8PDnSMg6MtNkz-ZxFUbrXGVNDTt9owaSm4qIJhJuOwhVsAurfWpUQ&usqp=CAU',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '3 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car4',
      title: 'Toyota Camry',
      location: 'Hyderabad, Telangana',
      rating: 4.5,
      price: 3000,
      totalPrice: 3600,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZO5FlhJUHJpYcLLtGAv3DrF7m3mGUPKqaqmVs_w-athwoci9fmY5rh-CIJGCeZdSfC3o&usqp=CAU',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '12 km away',
      availabilityDescription: 'Available from Monday',
    ),
    Property(
      id: 'car5',
      title: 'Honda City',
      location: 'Chennai, Tamil Nadu',
      rating: 4.4,
      price: 2500,
      totalPrice: 3000,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8hNK2ZL6BF7g4lCAIQUTC9pTrp3kx25gcKw&s',
      ],
      category: 'Cars',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '7 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'car6',
      title: 'Volkswagen Polo',
      location: 'Pune, Maharashtra',
      rating: 4.3,
      price: 2000,
      totalPrice: 2400,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC1BkIdW3kNi9rkBl-VPoDSA_OhhmSk8M-Nw&s',
      ],
      category: 'Cars',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '15 km away',
      availabilityDescription: 'Available this weekend',
    ),

    // Bikes (6 items)
    Property(
      id: 'bike1',
      title: 'Royal Enfield Classic 350',
      location: 'Jaipur, Rajasthan',
      rating: 4.7,
      price: 1500,
      totalPrice: 1800,
      images: [
        'https://i.pinimg.com/236x/2a/f3/1b/2af31bd45c46d3060d6291c58ed56b8d.jpg',
      ],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '4 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike2',
      title: 'Harley Davidson Iron 883',
      location: 'Goa, India',
      rating: 4.9,
      price: 3000,
      totalPrice: 3600,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbpY4Enm5mLpbtvB2JNgeAvFU1u6BLyVgJb89KyZ5mMtH6hMZmwdfXmicDuftvIRhha8s&usqp=CAU',
      ],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '6 km away',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'bike3',
      title: 'KTM Duke 390',
      location: 'Bangalore, Karnataka',
      rating: 4.6,
      price: 1800,
      totalPrice: 2160,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR19iI35JX5_mXH4uGRN5aK2HKaqp17bpkN9w&s',
      ],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '9 km away',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'bike4',
      title: 'Kawasaki Ninja 650',
      location: 'Mumbai, Maharashtra',
      rating: 4.8,
      price: 2500,
      totalPrice: 3000,
      images: [
        'https://assets.isu.pub/document-structure/221122075159-f6c58e623a792382bd077bfb654b7693/v1/c1a275d4b5099c467570b5c4283c9349.jpeg',
      ],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '11 km away',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'bike5',
      title: 'Yamaha R15',
      location: 'Delhi, India',
      rating: 4.5,
      price: 1200,
      totalPrice: 1440,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4EI-Kwx2maghB8eTiyjJ_nEyZEfiEOArVDQ&s',
      ],
      category: 'Bikes',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: '8 km away',
      availabilityDescription: 'Available from Monday',
    ),
    Property(
      id: 'bike6',
      title: 'Bajaj Dominar 400',
      location: 'Pune, Maharashtra',
      rating: 4.4,
      price: 1600,
      totalPrice: 1920,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTcBi3zhPaY6WCDKE5HwBP_PPVg7muZu4URg&s',
      ],
      category: 'Bikes',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: '5 km away',
      availabilityDescription: 'Available this weekend',
    ),

    // Laptops (6 items)
    Property(
      id: 'laptop1',
      title: 'MacBook Pro M1',
      location: 'Mumbai, Maharashtra',
      rating: 4.9,
      price: 2500,
      totalPrice: 3000,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXaMbDfLSF2ccPrDb9c-gTo4_PHL9kwtAfWflrHHCSAW3YWs5WuqWCbbNH584AbsWZ_Ak&usqp=CAU',
      ],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Central Mumbai',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'laptop2',
      title: 'Dell XPS 13',
      location: 'Bangalore, Karnataka',
      rating: 4.7,
      price: 2000,
      totalPrice: 2400,
      images: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnD4Je-2NyMGkfCjB4r5a9IjA3Z_A-56i4PQ&s',
      ],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Koramangala',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'laptop3',
      title: 'HP Spectre x360',
      location: 'Delhi, India',
      rating: 4.6,
      price: 1800,
      totalPrice: 2160,
      images: [
        'http://5.imimg.com/data5/SELLER/Default/2022/12/TY/KK/IJ/27290580/laptops-for-rental-500x500.jpeg',
      ],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'South Delhi',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'laptop4',
      title: 'Lenovo ThinkPad X1',
      location: 'Hyderabad, Telangana',
      rating: 4.5,
      price: 1900,
      totalPrice: 2280,
      images: [
        'https://5.imimg.com/data5/SELLER/Default/2022/12/KO/JY/MW/27290580/laptops-for-rental-1000x1000.jpeg',
      ],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Hitec City',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'laptop5',
      title: 'Asus ROG Zephyrus',
      location: 'Chennai, Tamil Nadu',
      rating: 4.8,
      price: 2200,
      totalPrice: 2640,
      images: [
        'http://5.imimg.com/data5/ANDROID/Default/2023/10/357430289/PN/BX/EO/88753913/product-jpeg-1000x1000.jpg',
      ],
      category: 'Laptops',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'T Nagar',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'laptop6',
      title: 'Acer Predator',
      location: 'Pune, Maharashtra',
      rating: 4.4,
      price: 1700,
      totalPrice: 2040,
      images: [
        'https://5.imimg.com/data5/ANDROID/Default/2023/10/357430223/AH/TH/YQ/88753913/product-jpeg-1000x1000.jpg',
      ],
      category: 'Laptops',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Kothrud',
      availabilityDescription: 'Available from Monday',
    ),

    // Cameras (6 items)
    Property(
      id: 'camera1',
      title: 'Canon EOS R5',
      location: 'Mumbai, Maharashtra',
      rating: 4.9,
      price: 3000,
      totalPrice: 3600,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipMNDBDZEx-hn95mlWEOYUsJRP09N176RYRt18YU=s1360-w1360-h1020',
      ],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Andheri',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera2',
      title: 'Sony A7 III',
      location: 'Delhi, India',
      rating: 4.8,
      price: 2800,
      totalPrice: 3360,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipPFua71qRx2ffjZbrLGah2c7eD5dFpdjgbR0uq9=s1360-w1360-h1020',
      ],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Connaught Place',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'camera3',
      title: 'Nikon Z6',
      location: 'Bangalore, Karnataka',
      rating: 4.7,
      price: 2500,
      totalPrice: 3000,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipOyOBLLascBmyk2vAo4uAiPRFl9RNpgsJ9OOrWq=s1360-w1360-h1020',
      ],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Indiranagar',
      availabilityDescription: 'Available tomorrow',
    ),
    Property(
      id: 'camera4',
      title: 'Fujifilm X-T4',
      location: 'Chennai, Tamil Nadu',
      rating: 4.6,
      price: 2200,
      totalPrice: 2640,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipN2gGHpLO4JMOEB5jxm00czvoxLJdp-WUaWjoSn=s1360-w1360-h1020',
      ],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Adyar',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'camera5',
      title: 'Panasonic GH5',
      location: 'Hyderabad, Telangana',
      rating: 4.5,
      price: 2000,
      totalPrice: 2400,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipNZkrAvT4mPbW9zsOkfckjTlD51KpCGTDUi2bC8=s1360-w1360-h1020',
      ],
      category: 'Cameras',
      isGuestFavorite: false,
      hasMap: false,
      distanceDescription: 'Banjara Hills',
      availabilityDescription: 'Available today',
    ),
    Property(
      id: 'camera6',
      title: 'BlackMagic Pocket 6K',
      location: 'Pune, Maharashtra',
      rating: 4.8,
      price: 3500,
      totalPrice: 4200,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipP4tdK4VDXZ1Ycmc7ILd61GOsWrcRUSPX7ZEClj=s1360-w1360-h1020',
      ],
      category: 'Cameras',
      isGuestFavorite: true,
      hasMap: false,
      distanceDescription: 'Kalyani Nagar',
      availabilityDescription: 'Available this weekend',
    ),

    // Houses (6 items)
    Property(
      id: 'house1',
      title: '3 BHK Residential House',
      location: 'RAMESWARAM BAADAVA',
      rating: 4.9,
      price: 15000,
      totalPrice: 18000,
      images: [
        'https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jan/22/Photo_h470_w1080/a9fcf6c-32d9-4a8d-9817-603c1fe1fc9c_65250765_470_1080.jpg',
      ],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: 'Hill Station',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house2',
      title: '2BHK House Villa',
      location: 'East Godavari, India',
      rating: 4.8,
      price: 12000,
      totalPrice: 14400,
      images: [
        'https://imgs.nestimg.com/2_bhk_independent_builder_floor_in_rajeshwari_nagar_for_rent_kakinada_the_reference_number_is_16396617_7020008738059723899.jpg',
      ],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: 'Calangute Beach',
      availabilityDescription: 'Available this weekend',
    ),
    Property(
      id: 'house3',
      title: 'Commercial Shops',
      location: 'Ravulapalem, East Godavarai',
      rating: 4.7,
      price: 8000,
      totalPrice: 9600,
      images: [
        'https://dynamic.realestateindia.com/prop_images/1847780/904248_2.jpg',
      ],
      category: 'Houses',
      isGuestFavorite: false,
      hasMap: true,
      distanceDescription: 'Near Mall Road',
      availabilityDescription: 'Available next week',
    ),
    Property(
      id: 'house4',
      title: 'Bridge Country Villas',
      location: 'Rajamundry, India',
      rating: 4.6,
      price: 10000,
      totalPrice: 12000,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipNixVSqCDoIooYeGPylBmQxl2SXtUKvPkYXPGco=s1360-w1360-h1020',
      ],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: 'Bandra West',
      availabilityDescription: 'Available now',
    ),
    Property(
      id: 'house5',
      title: 'SB Ventures',
      location: 'Rajamundry',
      rating: 4.9,
      price: 20000,
      totalPrice: 24000,
      images: [
        'https://lh3.googleusercontent.com/p/AF1QipNzSTglrAulZ2YdFNnwnXvVaxJtrbqMr_CmmZn9=s1360-w1360-h1020',
      ],
      category: 'Houses',
      isGuestFavorite: true,
      hasMap: true,
      distanceDescription: 'Old City',
      availabilityDescription: 'Available today',
    ),
  ];

  // Public getter to retrieve the list
  List<Property> get allProperties => _allProperties;

  // Example: Toggling favorite status
  void toggleFavorite(Property property) {
    final index = _allProperties.indexWhere((p) => p.id == property.id);
    if (index != -1) {
      _allProperties[index].isFavorite = !_allProperties[index].isFavorite;
      notifyListeners();
    }
  }
}

class PropertyImage extends StatelessWidget {
  final Property property;

  PropertyImage({required this.property});

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(
      imageUrl: property.images[0],
      fit: BoxFit.cover,
      placeholder: (context, url) => Center(
        child: CircularProgressIndicator(),
      ),
      errorWidget: (context, url, error) => Image.asset(
        'assets/images/placeholder.png',
        fit: BoxFit.cover,
      ),
    );
  }
}
