// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwFt8SHjYPjvI0o27zAGkwlxbrDsC-gYs',
    appId: '1:170736783315:web:7e6a4ebfff89ce08d52926',
    messagingSenderId: '170736783315',
    projectId: 'leez-ptiz14',
    authDomain: 'leez-ptiz14.firebaseapp.com',
    storageBucket: 'leez-ptiz14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp-RmXwOZeSB7ipIQG02SJ1EftpaKquhw',
    appId: '1:170736783315:android:52c075bff566bae2d52926',
    messagingSenderId: '170736783315',
    projectId: 'leez-ptiz14',
    storageBucket: 'leez-ptiz14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPa8zWqtDVisRz4_KwSIXdCgKQ1BR_evs',
    appId: '1:170736783315:ios:8be623008609621cd52926',
    messagingSenderId: '170736783315',
    projectId: 'leez-ptiz14',
    storageBucket: 'leez-ptiz14.firebasestorage.app',
    iosClientId: '170736783315-jc2uj3dbkcir1vsd11q4tft3e686lucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.leez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPa8zWqtDVisRz4_KwSIXdCgKQ1BR_evs',
    appId: '1:170736783315:ios:8be623008609621cd52926',
    messagingSenderId: '170736783315',
    projectId: 'leez-ptiz14',
    storageBucket: 'leez-ptiz14.firebasestorage.app',
    iosClientId: '170736783315-jc2uj3dbkcir1vsd11q4tft3e686lucf.apps.googleusercontent.com',
    iosBundleId: 'com.example.leez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwFt8SHjYPjvI0o27zAGkwlxbrDsC-gYs',
    appId: '1:170736783315:web:efc13c6bdeb6aa07d52926',
    messagingSenderId: '170736783315',
    projectId: 'leez-ptiz14',
    authDomain: 'leez-ptiz14.firebaseapp.com',
    storageBucket: 'leez-ptiz14.firebasestorage.app',
  );
}
