// import 'package:flutter/material.dart';
// import 'package:flutter/cupertino.dart';
// import 'package:leez/screens/user/product/product.dart';
// import 'package:leez/models/property.dart';
// import 'dart:async';

// // Theme remains the same as before
// ThemeData _buildAppTheme() {
//   return ThemeData(
//     primaryColor: const Color.fromARGB(255, 0, 0, 0),
//     colorScheme: const ColorScheme.light(
//       primary: Color.fromARGB(255, 0, 0, 0),
//       secondary: Color(0xFF222222),
//     ),
//     appBarTheme: const AppBarTheme(
//       backgroundColor: Color.fromARGB(255, 255, 255, 255),
//       elevation: 0,
//       iconTheme: IconThemeData(color: Color(0xFF222222)),
//     ),
//     fontFamily: 'Cereal',
//     textTheme: const TextTheme(
//       bodyMedium: TextStyle(color: Color(0xFF222222)),
//       titleMedium: TextStyle(fontWeight: FontWeight.w500, color: Color(0xFF222222)),
//     ),
//   );
// }

// // Models and Widgets at the top level
// class Property {
//   final String id;
//   final String title;
//   final String location;
//   final double rating;
//   final int price;
//   final int totalPrice;
//   final List<String> images;
//   final String category;
//   final bool isGuestFavorite;
//   final bool hasMap;
//   final String distanceDescription;
//   final String availabilityDescription;
//   bool isFavorite;

//   Property({
//     required this.id,
//     required this.title,
//     required this.location,
//     required this.rating,
//     required this.price,
//     required this.totalPrice,
//     required this.images,
//     required this.category,
//     this.isGuestFavorite = false,
//     this.hasMap = false,
//     required this.distanceDescription,
//     required this.availabilityDescription,
//     this.isFavorite = false,
//   });
// }

// class CategoryItem {
//   final IconData icon;
//   final String label;

//   CategoryItem({required this.icon, required this.label});
// }

// class PropertyCard extends StatelessWidget {
//   final Property property;
//   final bool showTotalPrice;
//   final Function(Property) onFavoriteToggle;

//   const PropertyCard({
//     super.key,
//     required this.property,
//     required this.showTotalPrice,
//     required this.onFavoriteToggle,
//   });

//   @override
//   Widget build(BuildContext context) {
//     return GestureDetector(
//       onTap: () {
//         Navigator.push(
//           context,
//           MaterialPageRoute(
//             builder: (context) => ListingDetailPage(property: property),
//           ),
//         );
//       },
//       child: Column(
//         crossAxisAlignment: CrossAxisAlignment.start,
//         children: [
//           AspectRatio(
//             aspectRatio: 16 / 9, // Adjusted to match the image’s card aspect ratio
//             child: ClipRRect(
//               borderRadius: BorderRadius.circular(12),
//               child: Stack(
//                 fit: StackFit.expand,
//                 children: [
//                   Image.asset(
//                     property.images.first,
//                     fit: BoxFit.cover,
//                     errorBuilder: (context, error, stackTrace) {
//                       return Container(color: Colors.grey); // Fallback for missing images
//                     },
//                   ),
//                   if (property.isGuestFavorite)
//                     Positioned(
//                       top: 12,
//                       left: 12,
//                       child: Container(
//                         padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
//                         decoration: BoxDecoration(
//                           color: const Color.fromARGB(255, 255, 255, 255),
//                           borderRadius: BorderRadius.circular(8), // Slightly larger radius
//                           boxShadow: [
//                             BoxShadow(
//                               color: Colors.grey.withOpacity(0.2),
//                               blurRadius: 4,
//                               offset: const Offset(0, 2),
//                             ),
//                           ],
//                         ),
//                         child: Row(
//                           mainAxisSize: MainAxisSize.min,
//                           children: [
//                             Text(
//                               'Guest favourite',
//                               style: TextStyle(
//                                 color: Color(0xFF222222),
//                                 fontSize: 12,
//                                 fontWeight: FontWeight.w500,
//                               ),
//                             ),
//                             const SizedBox(width: 4),
//                             Icon(
//                               Icons.favorite,
//                               color: Color(0xFFFF5A5F),
//                               size: 14,
//                             ),
//                           ],
//                         ),
//                       ),
//                     ),
//                   Positioned(
//                     top: 12,
//                     right: 12,
//                     child: Container(

//                       child: IconButton(
//                         icon: Icon(
//                           property.isFavorite ? Icons.favorite : Icons.favorite_border,
//                           color: property.isFavorite ? const Color(0xFFFF5A5F) : const Color(0xFF222222),
//                           size: 24,
//                         ),
//                         onPressed: () => onFavoriteToggle(property),
//                         padding: EdgeInsets.zero,
//                         constraints: const BoxConstraints(),
//                       ),
//                     ),
//                   ),
//                   if (property.hasMap)
//                     Positioned(
//                       bottom: 12,
//                       right: 12,
//                       child: Container(
//                         padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
//                         decoration: BoxDecoration(
//                           color: const Color.fromARGB(255, 255, 255, 255),
//                           borderRadius: BorderRadius.circular(8),
//                           boxShadow: [
//                             BoxShadow(
//                               color: Colors.grey.withOpacity(0.2),
//                               blurRadius: 4,
//                               offset: const Offset(0, 2),
//                             ),
//                           ],
//                         ),
//                         child: Row(
//                           mainAxisSize: MainAxisSize.min,
//                           children: [
//                             Icon(Icons.map, size: 16, color: Color(0xFF222222)),
//                             const SizedBox(width: 4),
//                             Text(
//                               'Map',
//                               style: TextStyle(
//                                 fontSize: 12,
//                                 fontWeight: FontWeight.w500,
//                                 color: Color(0xFF222222),
//                               ),
//                             ),
//                           ],
//                         ),
//                       ),
//                     ),
//                 ],
//               ),
//             ),
//           ),
//           const SizedBox(height: 12),
//           Row(
//             crossAxisAlignment: CrossAxisAlignment.start,
//             children: [
//               Expanded(
//                 child: Column(
//                   crossAxisAlignment: CrossAxisAlignment.start,
//                   children: [
//                     Text(
//                       property.location,
//                       style: const TextStyle(
//                         color: Color(0xFF222222),
//                         fontSize: 16,
//                         fontWeight: FontWeight.w500,
//                       ),
//                     ),
//                     const SizedBox(height: 4),
//                     Text(
//                       property.distanceDescription,
//                       style: TextStyle(
//                         color: Color(0xFF717171),
//                         fontSize: 14,
//                       ),
//                     ),
//                     const SizedBox(height: 4),
//                     Text(
//                       property.availabilityDescription,
//                       style: TextStyle(
//                         color: Color(0xFF717171),
//                         fontSize: 14,
//                       ),
//                     ),
//                     const SizedBox(height: 8),
//                     RichText(
//                       text: TextSpan(
//                         style: TextStyle(color: Color(0xFF222222), fontSize: 14),
//                         children: [
//                           TextSpan(
//                             text: showTotalPrice
//                                 ? '₹${property.totalPrice}'
//                                 : '₹${property.price}',
//                             style: const TextStyle(
//                               fontWeight: FontWeight.w600,
//                             ),
//                           ),
//                           const TextSpan(
//                             text: ' night',
//                             style: TextStyle(
//                               color: Color(0xFF717171),
//                             ),
//                           ),
//                         ],
//                       ),
//                     ),
//                   ],
//                 ),
//               ),
//               const SizedBox(width: 8),
//               Column(
//                 crossAxisAlignment: CrossAxisAlignment.end,
//                 children: [
//                   Row(
//                     mainAxisSize: MainAxisSize.min,
//                     children: [
//                       Icon(
//                         Icons.star,
//                         size: 14,
//                         color: Color(0xFFFF5A5F), // Match the image’s star color
//                       ),
//                       const SizedBox(width: 4),
//                       Text(
//                         property.rating.toString(),
//                         style: const TextStyle(
//                           color: Color(0xFF222222),
//                           fontSize: 14,
//                           fontWeight: FontWeight.w500,
//                         ),
//                       ),
//                     ],
//                   ),
//                 ],
//               ),
//             ],
//           ),
//         ],
//       ),
//     );
//   }
// }


// class _SearchBar extends StatelessWidget {
//   final Function(String) onChanged;

//   const _SearchBar({required this.onChanged});

//   @override
//   Widget build(BuildContext context) {
//     return Container(
//       height: 48,
//       decoration: BoxDecoration(
//         color: const Color.fromARGB(255, 255, 255, 255),
//         borderRadius: BorderRadius.circular(24),
//         boxShadow: [
//           BoxShadow(
//             color: Colors.grey.withOpacity(0.2),
//             spreadRadius: 1,
//             blurRadius: 4,
//             offset: const Offset(0, 2), // Slight shadow for depth
//           ),
//         ],
//       ),
//       child: Row(
//         children: [
//           Expanded(
//             child: TextField(
//               onChanged: onChanged,
//               decoration: InputDecoration(
//                 hintText: 'Start your search',
//                 hintStyle: TextStyle(color: Color(0xFF717171), fontSize: 16),
//                 prefixIcon: Icon(Icons.search, color: Color(0xFF222222)),
//                 border: InputBorder.none,
//                 contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
//               ),
//             ),
//           ),
//           const Padding(
//             padding: EdgeInsets.only(right: 16),
//             child: Icon(
//               Icons.tune,
//               color: Color(0xFF222222),
//               size: 18,
//             ),
//           ),
//         ],
//       ),
//     );
//   }
// }


// class PropertiesService {
//   Future<List<Property>> getProperties() async {
//     // TODO: Implement actual data fetching logic
//     // This is a placeholder that returns an empty list
//     return [];
//   }
// }



// class HomeScreen extends StatefulWidget {
//   const HomeScreen({super.key});

//   @override
//   State<HomeScreen> createState() => _HomeScreenState();
// }

// class _HomeScreenState extends State<HomeScreen> {
//   final List<Property> _allProperties = [];
//   String _searchQuery = "";
//   int _selectedCategoryIndex = 0;
//   bool _showTotalPrice = false;

//   final List<CategoryItem> _categories = [
//   CategoryItem(icon: Icons.directions_car, label: 'Cars'),
//   CategoryItem(icon: Icons.motorcycle, label: 'Bikes'),
//   CategoryItem(icon: Icons.laptop, label: 'Laptops'),
//   CategoryItem(icon: Icons.camera_alt, label: 'Cameras'),
//   CategoryItem(icon: Icons.house, label: 'Houses'),
//   CategoryItem(icon: Icons.smartphone, label: 'Mobiles'),
//   CategoryItem(icon: Icons.pedal_bike, label: 'Cycles'),
//   CategoryItem(icon: Icons.checkroom, label: 'Clothes'),
//   CategoryItem(icon: Icons.watch, label: 'Accessories'),
//   CategoryItem(icon: Icons.category, label: 'Other'),// Lake icon
//   ];

//   @override
//   void initState() {
//     super.initState();
//     _loadProperties();
//   }

//   Future<void> _loadProperties() async {
//     await Future.delayed(const Duration(seconds: 1));
//     setState(() {
//       _allProperties.addAll(dummyProperties);
//     });
//   }

//   void _onSearchChanged(String query) {
//     setState(() {
//       _searchQuery = query;
//     });
//   }

//   List<Property> get _filteredProperties {
//     final selectedCategory = _categories[_selectedCategoryIndex].label;
//     return _allProperties.where((property) {
//       final matchesCategory = property.category == selectedCategory;
//       final matchesSearch = _searchQuery.isEmpty ||
//           property.title.toLowerCase().contains(_searchQuery.toLowerCase()) ||
//           property.location.toLowerCase().contains(_searchQuery.toLowerCase());
//       return matchesCategory && matchesSearch;
//     }).toList();
//   }

// @override
// Widget build(BuildContext context) {
//   return CustomScrollView(
//     slivers: [
//       // SliverAppBar for the scrolling app bar
//       SliverAppBar(
//         backgroundColor: const Color.fromARGB(255, 255, 255, 255),
//         elevation: 0,
//         pinned: false, // Set to false to let it scroll out of view
//         floating: false, // Set to false for a standard scroll behavior
//         expandedHeight: 117, // Adjust this height to accommodate search bar + categories
//         flexibleSpace: FlexibleSpaceBar(
//           background: Column(
//             children: [
//               // Search bar
//               Padding(
//                 padding: const EdgeInsets.all(16),
//                 child: _SearchBar(onChanged: _onSearchChanged),
//               ),
//               // Category icons
//               _buildCategoryIcons(),
//             ],
//           ),
//         ),
//       ),
//       // Property cards in SliverList
//       SliverPadding(
//         padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
//         sliver: SliverList(
//           delegate: SliverChildBuilderDelegate(
//             (context, index) => Padding(
//               padding: const EdgeInsets.only(bottom: 24),
//               child: PropertyCard(
//                 property: _filteredProperties[index],
//                 showTotalPrice: _showTotalPrice,
//                 onFavoriteToggle: (prop) {
//                   setState(() {
//                     prop.isFavorite = !prop.isFavorite;
//                   });
//                 },
//               ),
//             ),
//             childCount: _filteredProperties.length,
//           ),
//         ),
//       ),
//     ],
//   );
// }
// Widget _buildCategoryIcons() {
//     return Container(
//       height: 60, // Reduced height to match the image’s compact tabs
//       padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
//       child: ListView.separated(
//         scrollDirection: Axis.horizontal,
//         itemCount: _categories.length,
//         separatorBuilder: (_, __) => const SizedBox(width: 16),
//         itemBuilder: (context, index) {
//           final category = _categories[index];
//           final isSelected = _selectedCategoryIndex == index;
//           return GestureDetector(
//             onTap: () => setState(() => _selectedCategoryIndex = index),
//             child: Column(
//               mainAxisSize: MainAxisSize.min,
//               children: [
//                 Container(
//                   padding: const EdgeInsets.all(6),
//                   decoration: BoxDecoration(
//                     shape: BoxShape.circle,
//                     color: isSelected ? const Color.fromARGB(255, 0, 0, 0).withOpacity(0.1) : Colors.transparent,
//                   ),
//                   child: Icon(
//                     category.icon,
//                     color: isSelected ? const Color.fromARGB(255, 0, 0, 0) : const Color(0xFF717171),
//                     size: 16, // Slightly smaller to match the image
//                   ),
//                 ),
//                 const SizedBox(height: 2),
//                 Text(
//                   category.label,
//                   style: TextStyle(
//                     color: isSelected ? const Color.fromARGB(255, 0, 0, 0) : const Color(0xFF717171),
//                     fontSize: 10,
//                     fontWeight: isSelected ? FontWeight.w500 : FontWeight.normal,
//                   ),
//                 ),
//               ],
//             ),
//           );
// },
//       ),
//     );
//   }


// Widget _buildTotalPriceToggle() {
//   return Container(
//     padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
//     decoration: const BoxDecoration(
//       border: Border(bottom: BorderSide(color: Color(0xFFF5F5F5), width: 1)),
//     ),
//     child: Row(
//       mainAxisAlignment: MainAxisAlignment.spaceBetween,
//       children: [
//         Column(
//           crossAxisAlignment: CrossAxisAlignment.start,
//           children: [
//             const Text(
//               'Display total price',
//               style: TextStyle(
//                 color: Color(0xFF222222),
//                 fontSize: 16,
//                 fontWeight: FontWeight.w500,
//               ),
//             ),
//             const SizedBox(height: 4),
//             Text(
//               'Includes all fees, before taxes',
//               style: TextStyle(
//                 color: Color(0xFF717171),
//                 fontSize: 12,
//               ),
//             ),
//           ],
//         ),
//         CupertinoSwitch(
//           value: _showTotalPrice,
//           onChanged: (value) => setState(() => _showTotalPrice = value),
//           activeTrackColor: const Color.fromARGB(255, 0, 0, 0),
//           thumbColor: const Color.fromARGB(255, 255, 255, 255),
//           trackColor: Color.fromARGB(255, 255, 255, 255), // Inactive track color to match the image
//         ),
//       ],
//     ),
//   );
// }
// }
// // Ensure this file is in a valid Dart/Flutter project, e.g., lib/models/property.dart or lib/data/dummy_data.dart




















// final dummyProperties = [
//   // Houses (1 item as an example)
//   Property(
//     id: 'house6',
//     title: 'Suburban Home',
//     location: 'Chennai, India',
//     rating: 4.5,
//     price: 2100,
//     totalPrice: 2700,
//     images: ['assets/nat5.png'], // Ensure this asset is defined in pubspec.yaml
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available this weekend',
//     isFavorite: false,
//   ),
//   Property(
//     id: 'car1',
//     title: 'Sporty Car',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 2000,
//     totalPrice: 2500,
//     images: ['assets/car1.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '10 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car2',
//     title: 'Luxury Sedan',
//     location: 'Delhi, India',
//     rating: 4.8,
//     price: 3000,
//     totalPrice: 3500,
//     images: ['assets/car2.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '15 km away',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'car3',
//     title: 'Convertible',
//     location: 'Bangalore, India',
//     rating: 4.6,
//     price: 2500,
//     totalPrice: 3000,
//     images: ['assets/car3.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '20 km away',
//     availabilityDescription: 'Available next week',
//   ),
//   Property(
//     id: 'car4',
//     title: 'Compact Car',
//     location: 'Hyderabad, India',
//     rating: 4.2,
//     price: 1800,
//     totalPrice: 2200,
//     images: ['assets/car12.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '5 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car5',
//     title: 'Family SUV',
//     location: 'Chennai, India',
//     rating: 4.7,
//     price: 2800,
//     totalPrice: 3300,
//     images: ['assets/car_.jpg'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'car6',
//     title: 'Vintage Classic',
//     location: 'Kolkata, India',
//     rating: 4.4,
//     price: 2200,
//     totalPrice: 2700,
//     images: ['assets/car2.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '12 km away',
//     availabilityDescription: 'Available soon',
//   ),

//   // Bikes (6 items)
//   Property(
//     id: 'bike1',
//     title: 'Sports Bike',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 1500,
//     totalPrice: 1800,
//     images: ['assets/bike.jpg'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike2',
//     title: 'Cruiser Bike',
//     location: 'Delhi, India',
//     rating: 4.7,
//     price: 1600,
//     totalPrice: 1900,
//     images: ['assets/bike.jpg'],
//     category: 'Bikes',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '12 km away',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'bike3',
//     title: 'Electric Bike',
//     location: 'Bangalore, India',
//     rating: 4.8,
//     price: 1700,
//     totalPrice: 2000,
//     images: ['assets/bike.jpg'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '10 km away',
//     availabilityDescription: 'Available next week',
//   ),
//   Property(
//     id: 'bike4',
//     title: 'Classic Bike',
//     location: 'Hyderabad, India',
//     rating: 4.3,
//     price: 1400,
//     totalPrice: 1700,
//     images: ['assets/bike.jpg'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '6 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike5',
//     title: 'Adventure Bike',
//     location: 'Chennai, India',
//     rating: 4.6,
//     price: 1550,
//     totalPrice: 1850,
//     images: ['assets/bike.jpg'],
//     category: 'Bikes',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '9 km away',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'bike6',
//     title: 'Touring Bike',
//     location: 'Kolkata, India',
//     rating: 4.4,
//     price: 1500,
//     totalPrice: 1800,
//     images: ['assets/bike.jpg'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '11 km away',
//     availabilityDescription: 'Available soon',
//   ),

//   // Laptops (6 items)
//   Property(
//     id: 'laptop1',
//     title: 'Gaming Laptop',
//     location: 'Mumbai, India',
//     rating: 4.9,
//     price: 80000,
//     totalPrice: 85000,
//     images: ['assets/laptop1.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'laptop2',
//     title: 'Ultrabook',
//     location: 'Delhi, India',
//     rating: 4.8,
//     price: 75000,
//     totalPrice: 80000,
//     images: ['assets/laptop.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available today',
//   ),
//   Property(
//     id: 'laptop3',
//     title: 'Business Laptop',
//     location: 'Bangalore, India',
//     rating: 4.7,
//     price: 70000,
//     totalPrice: 75000,
//     images: ['assets/laptop1.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'laptop4',
//     title: 'Convertible Laptop',
//     location: 'Hyderabad, India',
//     rating: 4.6,
//     price: 68000,
//     totalPrice: 73000,
//     images: ['assets/laptop.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'laptop5',
//     title: '2-in-1 Laptop',
//     location: 'Chennai, India',
//     rating: 4.8,
//     price: 72000,
//     totalPrice: 77000,
//     images: ['assets/laptop1.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'laptop6',
//     title: 'Budget Laptop',
//     location: 'Kolkata, India',
//     rating: 4.5,
//     price: 60000,
//     totalPrice: 65000,
//     images: ['assets/laptop.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In stock',
//     availabilityDescription: 'Available soon',
//   ),

//   // Cameras (6 items)
//   Property(
//     id: 'camera1',
//     title: 'DSLR Camera',
//     location: 'Mumbai, India',
//     rating: 4.9,
//     price: 45000,
//     totalPrice: 48000,
//     images: ['assets/cam1.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera2',
//     title: 'Mirrorless Camera',
//     location: 'Delhi, India',
//     rating: 4.8,
//     price: 50000,
//     totalPrice: 53000,
//     images: ['assets/cam3.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available today',
//   ),
//   Property(
//     id: 'camera3',
//     title: 'Compact Camera',
//     location: 'Bangalore, India',
//     rating: 4.7,
//     price: 35000,
//     totalPrice: 38000,
//     images: ['assets/cam4.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available tomorrow',
//   ),
//   Property(
//     id: 'camera4',
//     title: 'Action Camera',
//     location: 'Hyderabad, India',
//     rating: 4.6,
//     price: 30000,
//     totalPrice: 33000,
//     images: ['assets/cam78.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera5',
//     title: 'Film Camera',
//     location: 'Chennai, India',
//     rating: 4.5,
//     price: 28000,
//     totalPrice: 31000,
//     images: ['assets/cam1.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available this weekend',
//   ),
//   Property(
//     id: 'camera6',
//     title: 'Point & Shoot',
//     location: 'Kolkata, India',
//     rating: 4.4,
//     price: 22000,
//     totalPrice: 25000,
//     images: ['assets/cam3.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'In store',
//     availabilityDescription: 'Available soon',
//   ),

//   // Houses (6 items)
//   Property(
//     id: 'house1',
//     title: 'Modern Farm House',
//     location: 'Coimbatore, India',
//     rating: 4.9,
//     price: 1836,
//     totalPrice: 2500,
//     images: ['assets/nat1.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '259 km away',
//     availabilityDescription: '5-9 Apr',
//   ),
//   Property(
//     id: 'house2',
//     title: 'Beachfront Villa',
//     location: 'Goa, India',
//     rating: 4.8,
//     price: 2549,
//     totalPrice: 3200,
//     images: ['assets/nat2.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '200 km away',
//     availabilityDescription: '10-15 Apr',
//   ),
//   Property(
//     id: 'house3',
//     title: 'Mountain Cabin',
//     location: 'Himalayas, India',
//     rating: 4.7,
//     price: 1899,
//     totalPrice: 2600,
//     images: ['assets/nat2.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '300 km away',
//     availabilityDescription: '15-20 Apr',
//   ),
//   Property(
//     id: 'house4',
//     title: 'Luxury Apartment',
//     location: 'Mumbai, India',
//     rating: 4.9,
//     price: 3249,
//     totalPrice: 4000,
//     images: ['assets/nat3.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '5 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'house5',
//     title: 'Urban Condo',
//     location: 'Bangalore, India',
//     rating: 4.6,
//     price: 2900,
//     totalPrice: 3500,
//     images: ['assets/nat4.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '3 km away',
//     availabilityDescription: 'Available today',
//   ),
//   // Cars (6 items)
//   Property(
//     id: 'car1',
//     title: 'Sporty Car',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 2000,
//     totalPrice: 2500,
//     images: ['assets/car1.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '10 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car2',
//     title: 'Luxury Sedan',
//     location: 'Delhi, India',
//     rating: 4.3,
//     price: 3000,
//     totalPrice: 3500,
//     images: ['assets/car2.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '15 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car3',
//     title: 'Compact Hatchback',
//     location: 'Bangalore, India',
//     rating: 4.0,
//     price: 1800,
//     totalPrice: 2200,
//     images: ['assets/car3.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car4',
//     title: 'Convertible',
//     location: 'Hyderabad, India',
//     rating: 4.8,
//     price: 4000,
//     totalPrice: 4500,
//     images: ['assets/car4.jpg'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '12 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car5',
//     title: 'SUV',
//     location: 'Chennai, India',
//     rating: 4.2,
//     price: 3500,
//     totalPrice: 4000,
//     images: ['assets/car5.png'],
//     category: 'Cars',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '20 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'car6',
//     title: 'Electric Car',
//     location: 'Kolkata, India',
//     rating: 4.7,
//     price: 3200,
//     totalPrice: 3700,
//     images: ['assets/car6.png'],
//     category: 'Cars',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '7 km away',
//     availabilityDescription: 'Available now',
//   ),

//   // Bikes (6 items)
//   Property(
//     id: 'bike1',
//     title: 'Sport Bike',
//     location: 'Mumbai, India',
//     rating: 4.3,
//     price: 800,
//     totalPrice: 950,
//     images: ['assets/bikes/bike1.png'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '3 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike2',
//     title: 'Cruiser Bike',
//     location: 'Delhi, India',
//     rating: 4.1,
//     price: 700,
//     totalPrice: 850,
//     images: ['assets/bikes/bike2.png'],
//     category: 'Bikes',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '5 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike3',
//     title: 'Electric Bike',
//     location: 'Bangalore, India',
//     rating: 4.5,
//     price: 900,
//     totalPrice: 1050,
//     images: ['assets/bikes/bike3.png'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '4 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike4',
//     title: 'Off-Road Bike',
//     location: 'Hyderabad, India',
//     rating: 4.4,
//     price: 750,
//     totalPrice: 900,
//     images: ['assets/bikes/bike4.png'],
//     category: 'Bikes',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '6 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike5',
//     title: 'Classic Bike',
//     location: 'Chennai, India',
//     rating: 4.0,
//     price: 650,
//     totalPrice: 800,
//     images: ['assets/bikes/bike5.png'],
//     category: 'Bikes',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '2 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'bike6',
//     title: 'Adventure Bike',
//     location: 'Kolkata, India',
//     rating: 4.6,
//     price: 950,
//     totalPrice: 1100,
//     images: ['assets/bikes/bike6.png'],
//     category: 'Bikes',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '8 km away',
//     availabilityDescription: 'Available now',
//   ),

//   // Laptops (6 items)
//   Property(
//     id: 'laptop1',
//     title: 'Gaming Laptop',
//     location: 'Mumbai, India',
//     rating: 4.7,
//     price: 50000,
//     totalPrice: 52000,
//     images: ['assets/laptops/laptop1.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'laptop2',
//     title: 'Ultrabook',
//     location: 'Delhi, India',
//     rating: 4.5,
//     price: 60000,
//     totalPrice: 63000,
//     images: ['assets/laptops/laptop2.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'laptop3',
//     title: 'Business Laptop',
//     location: 'Bangalore, India',
//     rating: 4.3,
//     price: 55000,
//     totalPrice: 57000,
//     images: ['assets/laptops/laptop3.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'laptop4',
//     title: 'Convertible Laptop',
//     location: 'Hyderabad, India',
//     rating: 4.6,
//     price: 65000,
//     totalPrice: 68000,
//     images: ['assets/laptops/laptop4.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'laptop5',
//     title: 'Budget Laptop',
//     location: 'Chennai, India',
//     rating: 4.0,
//     price: 40000,
//     totalPrice: 42000,
//     images: ['assets/laptops/laptop5.png'],
//     category: 'Laptops',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'laptop6',
//     title: 'High-Performance Laptop',
//     location: 'Kolkata, India',
//     rating: 4.8,
//     price: 70000,
//     totalPrice: 73000,
//     images: ['assets/laptops/laptop6.png'],
//     category: 'Laptops',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),

//   // Cameras (6 items)
//   Property(
//     id: 'camera1',
//     title: 'DSLR Camera',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 25000,
//     totalPrice: 27000,
//     images: ['assets/cameras/camera1.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Store Pickup',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera2',
//     title: 'Mirrorless Camera',
//     location: 'Delhi, India',
//     rating: 4.7,
//     price: 30000,
//     totalPrice: 32000,
//     images: ['assets/cameras/camera2.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Store Pickup',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera3',
//     title: 'Point & Shoot',
//     location: 'Bangalore, India',
//     rating: 4.2,
//     price: 15000,
//     totalPrice: 16500,
//     images: ['assets/cameras/camera3.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Store Pickup',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera4',
//     title: 'Action Camera',
//     location: 'Hyderabad, India',
//     rating: 4.4,
//     price: 18000,
//     totalPrice: 19500,
//     images: ['assets/cameras/camera4.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Store Pickup',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera5',
//     title: 'Film Camera',
//     location: 'Chennai, India',
//     rating: 4.0,
//     price: 12000,
//     totalPrice: 13500,
//     images: ['assets/cameras/camera5.png'],
//     category: 'Cameras',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Store Pickup',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'camera6',
//     title: 'Professional Camera',
//     location: 'Kolkata, India',
//     rating: 4.8,
//     price: 35000,
//     totalPrice: 37000,
//     images: ['assets/cameras/camera6.png'],
//     category: 'Cameras',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Store Pickup',
//     availabilityDescription: 'Available now',
//   ),

//   // Houses (6 items)
//   Property(
//     id: 'house1',
//     title: 'Luxury Villa',
//     location: 'Mumbai, India',
//     rating: 4.9,
//     price: 150000,
//     totalPrice: 160000,
//     images: ['assets/houses/house1.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '2 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'house2',
//     title: 'Modern Apartment',
//     location: 'Delhi, India',
//     rating: 4.4,
//     price: 90000,
//     totalPrice: 95000,
//     images: ['assets/houses/house2.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '5 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'house3',
//     title: 'Cozy Cottage',
//     location: 'Bangalore, India',
//     rating: 4.2,
//     price: 70000,
//     totalPrice: 75000,
//     images: ['assets/houses/house3.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '7 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'house4',
//     title: 'Penthouse Suite',
//     location: 'Hyderabad, India',
//     rating: 4.8,
//     price: 200000,
//     totalPrice: 210000,
//     images: ['assets/houses/house4.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '1 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'house5',
//     title: 'Suburban Home',
//     location: 'Chennai, India',
//     rating: 4.3,
//     price: 80000,
//     totalPrice: 85000,
//     images: ['assets/houses/house5.png'],
//     category: 'Houses',
//     isGuestFavorite: false,
//     hasMap: true,
//     distanceDescription: '6 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'house6',
//     title: 'Beachside Bungalow',
//     location: 'Kolkata, India',
//     rating: 4.7,
//     price: 120000,
//     totalPrice: 125000,
//     images: ['assets/houses/house6.png'],
//     category: 'Houses',
//     isGuestFavorite: true,
//     hasMap: true,
//     distanceDescription: '3 km away',
//     availabilityDescription: 'Available now',
//   ),

//   // Mobiles (6 items)
//   Property(
//     id: 'mobile1',
//     title: 'Smartphone X',
//     location: 'Mumbai, India',
//     rating: 4.6,
//     price: 30000,
//     totalPrice: 31000,
//     images: ['assets/mobiles/mobile1.png'],
//     category: 'Mobiles',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'mobile2',
//     title: 'Smartphone Y',
//     location: 'Delhi, India',
//     rating: 4.4,
//     price: 28000,
//     totalPrice: 29000,
//     images: ['assets/mobiles/mobile2.png'],
//     category: 'Mobiles',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'mobile3',
//     title: 'Budget Smartphone',
//     location: 'Bangalore, India',
//     rating: 4.1,
//     price: 15000,
//     totalPrice: 16000,
//     images: ['assets/mobiles/mobile3.png'],
//     category: 'Mobiles',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'mobile4',
//     title: 'Flagship Smartphone',
//     location: 'Hyderabad, India',
//     rating: 4.8,
//     price: 45000,
//     totalPrice: 46000,
//     images: ['assets/mobiles/mobile4.png'],
//     category: 'Mobiles',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'mobile5',
//     title: 'Gaming Smartphone',
//     location: 'Chennai, India',
//     rating: 4.5,
//     price: 40000,
//     totalPrice: 41000,
//     images: ['assets/mobiles/mobile5.png'],
//     category: 'Mobiles',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'mobile6',
//     title: 'Compact Smartphone',
//     location: 'Kolkata, India',
//     rating: 4.3,
//     price: 22000,
//     totalPrice: 23000,
//     images: ['assets/mobiles/mobile6.png'],
//     category: 'Mobiles',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),

//   // Cycles (6 items)
//   Property(
//     id: 'cycle1',
//     title: 'Mountain Bike',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 5000,
//     totalPrice: 5200,
//     images: ['assets/cycles/cycle1.png'],
//     category: 'Cycles',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '2 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'cycle2',
//     title: 'Road Bike',
//     location: 'Delhi, India',
//     rating: 4.3,
//     price: 4500,
//     totalPrice: 4700,
//     images: ['assets/cycles/cycle2.png'],
//     category: 'Cycles',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '3 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'cycle3',
//     title: 'Hybrid Bike',
//     location: 'Bangalore, India',
//     rating: 4.2,
//     price: 4800,
//     totalPrice: 5000,
//     images: ['assets/cycles/cycle3.png'],
//     category: 'Cycles',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '4 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'cycle4',
//     title: 'Electric Cycle',
//     location: 'Hyderabad, India',
//     rating: 4.6,
//     price: 6000,
//     totalPrice: 6300,
//     images: ['assets/cycles/cycle4.png'],
//     category: 'Cycles',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '1 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'cycle5',
//     title: 'Folding Bike',
//     location: 'Chennai, India',
//     rating: 4.0,
//     price: 4000,
//     totalPrice: 4200,
//     images: ['assets/cycles/cycle5.png'],
//     category: 'Cycles',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: '3 km away',
//     availabilityDescription: 'Available now',
//   ),
//   Property(
//     id: 'cycle6',
//     title: 'City Bike',
//     location: 'Kolkata, India',
//     rating: 4.4,
//     price: 4300,
//     totalPrice: 4500,
//     images: ['assets/cycles/cycle6.png'],
//     category: 'Cycles',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: '2 km away',
//     availabilityDescription: 'Available now',
//   ),

//   // Clothes (6 items)
//   Property(
//     id: 'clothes1',
//     title: 'Men\'s Jacket',
//     location: 'Mumbai, India',
//     rating: 4.5,
//     price: 2000,
//     totalPrice: 2100,
//     images: ['assets/clothes/clothes1.png'],
//     category: 'Clothes',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'clothes2',
//     title: 'Women\'s Dress',
//     location: 'Delhi, India',
//     rating: 4.7,
//     price: 2500,
//     totalPrice: 2600,
//     images: ['assets/clothes/clothes2.png'],
//     category: 'Clothes',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'clothes3',
//     title: 'Casual Shirt',
//     location: 'Bangalore, India',
//     rating: 4.2,
//     price: 1500,
//     totalPrice: 1600,
//     images: ['assets/clothes/clothes3.png'],
//     category: 'Clothes',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'clothes4',
//     title: 'Jeans',
//     location: 'Hyderabad, India',
//     rating: 4.4,
//     price: 1800,
//     totalPrice: 1900,
//     images: ['assets/clothes/clothes4.png'],
//     category: 'Clothes',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'clothes5',
//     title: 'Sneakers',
//     location: 'Chennai, India',
//     rating: 4.1,
//     price: 2200,
//     totalPrice: 2300,
//     images: ['assets/clothes/clothes5.png'],
//     category: 'Clothes',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'clothes6',
//     title: 'Sportswear',
//     location: 'Kolkata, India',
//     rating: 4.6,
//     price: 2800,
//     totalPrice: 2900,
//     images: ['assets/clothes/clothes6.png'],
//     category: 'Clothes',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),

//   // Accessories (6 items)
//   Property(
//     id: 'accessory1',
//     title: 'Wrist Watch',
//     location: 'Mumbai, India',
//     rating: 4.7,
//     price: 3500,
//     totalPrice: 3600,
//     images: ['assets/accessories/accessory1.png'],
//     category: 'Accessories',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'accessory2',
//     title: 'Sunglasses',
//     location: 'Delhi, India',
//     rating: 4.4,
//     price: 1500,
//     totalPrice: 1600,
//     images: ['assets/accessories/accessory2.png'],
//     category: 'Accessories',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'accessory3',
//     title: 'Leather Belt',
//     location: 'Bangalore, India',
//     rating: 4.3,
//     price: 1200,
//     totalPrice: 1300,
//     images: ['assets/accessories/accessory3.png'],
//     category: 'Accessories',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'accessory4',
//     title: 'Handbag',
//     location: 'Hyderabad, India',
//     rating: 4.6,
//     price: 2800,
//     totalPrice: 2900,
//     images: ['assets/accessories/accessory4.png'],
//     category: 'Accessories',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'accessory5',
//     title: 'Scarf',
//     location: 'Chennai, India',
//     rating: 4.1,
//     price: 900,
//     totalPrice: 1000,
//     images: ['assets/accessories/accessory5.png'],
//     category: 'Accessories',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),
//   Property(
//     id: 'accessory6',
//     title: 'Beanie',
//     location: 'Kolkata, India',
//     rating: 4.5,
//     price: 800,
//     totalPrice: 900,
//     images: ['assets/accessories/accessory6.png'],
//     category: 'Accessories',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'In stock',
//   ),

//   // Other (6 items)
//   Property(
//     id: 'other1',
//     title: 'Vintage Record Player',
//     location: 'Mumbai, India',
//     rating: 4.6,
//     price: 5000,
//     totalPrice: 5200,
//     images: ['assets/other/other1.png'],
//     category: 'Other',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'Limited stock',
//   ),
//   Property(
//     id: 'other2',
//     title: 'Antique Clock',
//     location: 'Delhi, India',
//     rating: 4.3,
//     price: 3200,
//     totalPrice: 3400,
//     images: ['assets/other/other2.png'],
//     category: 'Other',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'Limited stock',
//   ),
//   Property(
//     id: 'other3',
//     title: 'Handcrafted Lamp',
//     location: 'Bangalore, India',
//     rating: 4.4,
//     price: 2700,
//     totalPrice: 2900,
//     images: ['assets/other/other3.png'],
//     category: 'Other',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'Limited stock',
//   ),
//   Property(
//     id: 'other4',
//     title: 'Designer Vase',
//     location: 'Hyderabad, India',
//     rating: 4.5,
//     price: 3500,
//     totalPrice: 3700,
//     images: ['assets/other/other4.png'],
//     category: 'Other',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'Limited stock',
//   ),
//   Property(
//     id: 'other5',
//     title: 'Modern Art Sculpture',
//     location: 'Chennai, India',
//     rating: 4.7,
//     price: 4500,
//     totalPrice: 4700,
//     images: ['assets/other/other5.png'],
//     category: 'Other',
//     isGuestFavorite: true,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'Limited stock',
//   ),
//   Property(
//     id: 'other6',
//     title: 'Contemporary Wall Art',
//     location: 'Kolkata, India',
//     rating: 4.2,
//     price: 2800,
//     totalPrice: 3000,
//     images: ['assets/other/other6.png'],
//     category: 'Other',
//     isGuestFavorite: false,
//     hasMap: false,
//     distanceDescription: 'Online Deal',
//     availabilityDescription: 'Limited stock',
//   ),
//     // Cars (6 items)
//     Property(
//       id: 'car1',
//       title: 'Sporty Car',
//       location: 'Mumbai, India',
//       rating: 4.5,
//       price: 2000,
//       totalPrice: 2500,
//       images: ['assets/car1.png'],
//       category: 'Cars',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '10 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'car2',
//       title: 'Luxury Sedan',
//       location: 'Delhi, India',
//       rating: 4.7,
//       price: 3000,
//       totalPrice: 3500,
//       images: ['assets/car2.png'],
//       category: 'Cars',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
//     Property(
//       id: 'car3',
//       title: 'Compact SUV',
//       location: 'Bangalore, India',
//       rating: 4.3,
//       price: 2500,
//       totalPrice: 3000,
//       images: ['assets/car3.png'],
//       category: 'Cars',
//       isGuestFavorite: true,
//       hasMap: false,
//       distanceDescription: '15 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'car4',
//       title: 'Electric Hatchback',
//       location: 'Hyderabad, India',
//       rating: 4.8,
//       price: 2200,
//       totalPrice: 2700,
//       images: ['assets/car4.jpg'],
//       category: 'Cars',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '8 km away',
//       availabilityDescription: 'Available next week',
//     ),
//     Property(
//       id: 'car5',
//       title: 'Premium Coupe',
//       location: 'Chennai, India',
//       rating: 4.6,
//       price: 4000,
//       totalPrice: 4500,
//       images: ['assets/car5.png'],
//       category: 'Cars',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '12 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'car6',
//       title: 'Family Minivan',
//       location: 'Pune, India',
//       rating: 4.2,
//       price: 2800,
//       totalPrice: 3300,
//       images: ['assets/car6.png'],
//       category: 'Cars',
//       isGuestFavorite: false,
//       hasMap: false,
//       distanceDescription: '20 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
  
//     // Bikes (6 items)
//     Property(
//       id: 'bike1',
//       title: 'Sport Bike',
//       location: 'Mumbai, India',
//       rating: 4.4,
//       price: 800,
//       totalPrice: 1000,
//       images: ['https://example.com/bike1.jpg'],
//       category: 'Bikes',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'bike2',
//       title: 'Cruiser Bike',
//       location: 'Delhi, India',
//       rating: 4.6,
//       price: 1200,
//       totalPrice: 1400,
//       images: ['https://example.com/bike2.jpg'],
//       category: 'Bikes',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '10 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
//     Property(
//       id: 'bike3',
//       title: 'Electric Scooter',
//       location: 'Bangalore, India',
//       rating: 4.5,
//       price: 600,
//       totalPrice: 800,
//       images: ['https://example.com/bike3.jpg'],
//       category: 'Bikes',
//       isGuestFavorite: true,
//       hasMap: false,
//       distanceDescription: '3 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'bike4',
//       title: 'Adventure Bike',
//       location: 'Hyderabad, India',
//       rating: 4.7,
//       price: 1500,
//       totalPrice: 1700,
//       images: ['https://example.com/bike4.jpg'],
//       category: 'Bikes',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '7 km away',
//       availabilityDescription: 'Available next week',
//     ),
//     Property(
//       id: 'bike5',
//       title: 'Classic Bike',
//       location: 'Chennai, India',
//       rating: 4.3,
//       price: 1000,
//       totalPrice: 1200,
//       images: ['https://example.com/bike5.jpg'],
//       category: 'Bikes',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '12 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'bike6',
//       title: 'Off-Road Bike',
//       location: 'Pune, India',
//       rating: 4.2,
//       price: 900,
//       totalPrice: 1100,
//       images: ['https://example.com/bike6.jpg'],
//       category: 'Bikes',
//       isGuestFavorite: false,
//       hasMap: false,
//       distanceDescription: '15 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
  
//     // Laptops (6 items)
//     Property(
//       id: 'laptop1',
//       title: 'Gaming Laptop',
//       location: 'Mumbai, India',
//       rating: 4.5,
//       price: 80000,
//       totalPrice: 85000,
//       images: ['https://example.com/laptop1.jpg'],
//       category: 'Laptops',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '2 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'laptop2',
//       title: 'Ultrabook',
//       location: 'Delhi, India',
//       rating: 4.7,
//       price: 70000,
//       totalPrice: 75000,
//       images: ['https://example.com/laptop2.jpg'],
//       category: 'Laptops',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
//     Property(
//       id: 'laptop3',
//       title: 'MacBook Pro',
//       location: 'Bangalore, India',
//       rating: 4.8,
//       price: 120000,
//       totalPrice: 125000,
//       images: ['https://example.com/laptop3.jpg'],
//       category: 'Laptops',
//       isGuestFavorite: true,
//       hasMap: false,
//       distanceDescription: '10 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'laptop4',
//       title: 'Budget Laptop',
//       location: 'Hyderabad, India',
//       rating: 4.2,
//       price: 40000,
//       totalPrice: 45000,
//       images: ['https://example.com/laptop4.jpg'],
//       category: 'Laptops',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '7 km away',
//       availabilityDescription: 'Available next week',
//     ),
//     Property(
//       id: 'laptop5',
//       title: '2-in-1 Laptop',
//       location: 'Chennai, India',
//       rating: 4.6,
//       price: 90000,
//       totalPrice: 95000,
//       images: ['https://example.com/laptop5.jpg'],
//       category: 'Laptops',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '12 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'laptop6',
//       title: 'Workstation Laptop',
//       location: 'Pune, India',
//       rating: 4.4,
//       price: 100000,
//       totalPrice: 105000,
//       images: ['https://example.com/laptop6.jpg'],
//       category: 'Laptops',
//       isGuestFavorite: false,
//       hasMap: false,
//       distanceDescription: '15 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
  
//     // Cameras (6 items)
//     Property(
//       id: 'camera1',
//       title: 'DSLR Camera',
//       location: 'Mumbai, India',
//       rating: 4.5,
//       price: 50000,
//       totalPrice: 55000,
//       images: ['https://example.com/camera1.jpg'],
//       category: 'Cameras',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '2 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'camera2',
//       title: 'Mirrorless Camera',
//       location: 'Delhi, India',
//       rating: 4.7,
//       price: 60000,
//       totalPrice: 65000,
//       images: ['https://example.com/camera2.jpg'],
//       category: 'Cameras',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
//     Property(
//       id: 'camera3',
//       title: 'Action Camera',
//       location: 'Bangalore, India',
//       rating: 4.6,
//       price: 25000,
//       totalPrice: 30000,
//       images: ['https://example.com/camera3.jpg'],
//       category: 'Cameras',
//       isGuestFavorite: true,
//       hasMap: false,
//       distanceDescription: '10 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'camera4',
//       title: 'Instant Camera',
//       location: 'Hyderabad, India',
//       rating: 4.3,
//       price: 15000,
//       totalPrice: 20000,
//       images: ['https://example.com/camera4.jpg'],
//       category: 'Cameras',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '7 km away',
//       availabilityDescription: 'Available next week',
//     ),
//     Property(
//       id: 'camera5',
//       title: 'Vlogging Camera',
//       location: 'Chennai, India',
//       rating: 4.8,
//       price: 70000,
//       totalPrice: 75000,
//       images: ['https://example.com/camera5.jpg'],
//       category: 'Cameras',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '12 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'camera6',
//       title: 'Compact Camera',
//       location: 'Pune, India',
//       rating: 4.2,
//       price: 20000,
//       totalPrice: 25000,
//       images: ['https://example.com/camera6.jpg'],
//       category: 'Cameras',
//       isGuestFavorite: false,
//       hasMap: false,
//       distanceDescription: '15 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
  
//     // Houses (6 items)
//     Property(
//       id: 'house1',
//       title: 'Luxury Villa',
//       location: 'Mumbai, India',
//       rating: 4.5,
//       price: 20000,
//       totalPrice: 25000,
//       images: ['https://example.com/house1.jpg'],
//       category: 'Houses',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '2 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'house2',
//       title: 'Beach House',
//       location: 'Goa, India',
//       rating: 4.7,
//       price: 30000,
//       totalPrice: 35000,
//       images: ['https://example.com/house2.jpg'],
//       category: 'Houses',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
//     Property(
//       id: 'house3',
//       title: 'Mountain Cabin',
//       location: 'Manali, India',
//       rating: 4.6,
//       price: 15000,
//       totalPrice: 20000,
//       images: ['https://example.com/house3.jpg'],
//       category: 'Houses',
//       isGuestFavorite: true,
//       hasMap: false,
//       distanceDescription: '10 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'house4',
//       title: 'City Apartment',
//       location: 'Delhi, India',
//       rating: 4.3,
//       price: 12000,
//       totalPrice: 17000,
//       images: ['https://example.com/house4.jpg'],
//       category: 'Houses',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '7 km away',
//       availabilityDescription: 'Available next week',
//     ),
//     Property(
//       id: 'house5',
//       title: 'Farmhouse',
//       location: 'Pune, India',
//       rating: 4.8,
//       price: 25000,
//       totalPrice: 30000,
//       images: ['https://example.com/house5.jpg'],
//       category: 'Houses',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '12 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'house6',
//       title: 'Studio Apartment',
//       location: 'Bangalore, India',
//       rating: 4.2,
//       price: 10000,
//       totalPrice: 15000,
//       images: ['https://example.com/house6.jpg'],
//       category: 'Houses',
//       isGuestFavorite: false,
//       hasMap: false,
//       distanceDescription: '15 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
  
//     // Mobiles (6 items)
//     Property(
//       id: 'mobile1',
//       title: 'Flagship Smartphone',
//       location: 'Mumbai, India',
//       rating: 4.5,
//       price: 50000,
//       totalPrice: 55000,
//       images: ['https://example.com/mobile1.jpg'],
//       category: 'Mobiles',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '2 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'mobile2',
//       title: 'Budget Smartphone',
//       location: 'Delhi, India',
//       rating: 4.7,
//       price: 15000,
//       totalPrice: 20000,
//       images: ['https://example.com/mobile2.jpg'],
//       category: 'Mobiles',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
//     Property(
//       id: 'mobile3',
//       title: 'Gaming Phone',
//       location: 'Bangalore, India',
//       rating: 4.6,
//       price: 40000,
//       totalPrice: 45000,
//       images: ['https://example.com/mobile3.jpg'],
//       category: 'Mobiles',
//       isGuestFavorite: true,
//       hasMap: false,
//       distanceDescription: '10 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'mobile4',
//       title: 'Camera Phone',
//       location: 'Hyderabad, India',
//       rating: 4.3,
//       price: 30000,
//       totalPrice: 35000,
//       images: ['https://example.com/mobile4.jpg'],
//       category: 'Mobiles',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '7 km away',
//       availabilityDescription: 'Available next week',
//     ),
//     Property(
//       id: 'mobile5',
//       title: 'Foldable Phone',
//       location: 'Chennai, India',
//       rating: 4.8,
//       price: 100000,
//       totalPrice: 105000,
//       images: ['https://example.com/mobile5.jpg'],
//       category: 'Mobiles',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '12 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'mobile6',
//       title: 'Mid-Range Phone',
//       location: 'Pune, India',
//       rating: 4.2,
//       price: 20000,
//       totalPrice: 25000,
//       images: ['https://example.com/mobile6.jpg'],
//       category: 'Mobiles',
//       isGuestFavorite: false,
//       hasMap: false,
//       distanceDescription: '15 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
  
//     // Cycles (6 items)
//     Property(
//       id: 'cycle1',
//       title: 'Mountain Bike',
//       location: 'Mumbai, India',
//       rating: 4.5,
//       price: 8000,
//       totalPrice: 8500,
//       images: ['https://example.com/cycle1.jpg'],
//       category: 'Cycles',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '2 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'cycle2',
//       title: 'Road Bike',
//       location: 'Delhi, India',
//       rating: 4.7,
//       price: 12000,
//       totalPrice: 12500,
//       images: ['https://example.com/cycle2.jpg'],
//       category: 'Cycles',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available tomorrow',
//     ),
//     // Cars (6 items)
//     Property(
//       id: 'car1',
//       title: 'Sporty Car',
//       location: 'Mumbai, India',
//       rating: 4.5,
//       price: 2000,
//       totalPrice: 2500,
//       images: ['assets/car1.png'],
//       category: 'Cars',
//       isGuestFavorite: true,
//       hasMap: true,
//       distanceDescription: '10 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'car2',
//       title: 'Luxury Sedan',
//       location: 'Delhi, India',
//       rating: 4.7,
//       price: 3000,
//       totalPrice: 3500,
//       images: ['assets/car2.png'],
//       category: 'Cars',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '5 km away',
//       availabilityDescription: 'Available from tomorrow',
//     ),
//     Property(
//       id: 'car3',
//       title: 'Compact SUV',
//       location: 'Bangalore, India',
//       rating: 4.3,
//       price: 2500,
//       totalPrice: 3000,
//       images: ['assets/car3.png'],
//       category: 'Cars',
//       isGuestFavorite: true,
//       hasMap: false,
//       distanceDescription: '15 km away',
//       availabilityDescription: 'Available now',
//     ),
//     Property(
//       id: 'car4',
//       title: 'Electric Hatchback',
//       location: 'Hyderabad, India',
//       rating: 4.8,
//       price: 2200,
//       totalPrice: 2700,
//       images: ['assets/car4.jpg'],
//       category: 'Cars',
//       isGuestFavorite: false,
//       hasMap: true,
//       distanceDescription: '8 km away',
//       availabilityDescription: 'Available next week',
//     ),

//       // Cars (6 items)
//       Property(
//         id: 'car1',
//         title: 'BMW 3 Series',
//         location: 'Mumbai, Maharashtra',
//         rating: 4.8,
//         price: 5000,
//         totalPrice: 6000,
//         images: ['assets/cars/bmw3.avif'],
//         category: 'Cars',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: '5 km away',
//         availabilityDescription: 'Available today',
//       ),
//       Property(
//         id: 'car2',
//         title: 'Mercedes C-Class',
//         location: 'Delhi, India',
//         rating: 4.7,
//         price: 6000,
//         totalPrice: 7200,
//         images: ['assets/cars/merc.avif'],
//         category: 'Cars',
//         isGuestFavorite: false,
//         hasMap: true,
//         distanceDescription: '8 km away',
//         availabilityDescription: 'Available tomorrow',
//       ),
//       Property(
//         id: 'car3',
//         title: 'Audi A4',
//         location: 'Bangalore, Karnataka',
//         rating: 4.6,
//         price: 5500,
//         totalPrice: 6600,
//         images: ['assets/cars/audi.avif'],
//         category: 'Cars',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: '3 km away',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'car4',
//         title: 'Toyota Camry',
//         location: 'Hyderabad, Telangana',
//         rating: 4.5,
//         price: 3000,
//         totalPrice: 3600,
//         images: ['assets/cars/camry.jpg'],
//         category: 'Cars',
//         isGuestFavorite: false,
//         hasMap: true,
//         distanceDescription: '12 km away',
//         availabilityDescription: 'Available from Monday',
//       ),
//       Property(
//         id: 'car5',
//         title: 'Honda City',
//         location: 'Chennai, Tamil Nadu',
//         rating: 4.4,
//         price: 2500,
//         totalPrice: 3000,
//         images: ['assets/cars/city.jpg'],
//         category: 'Cars',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: '7 km away',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'car6',
//         title: 'Volkswagen Polo',
//         location: 'Pune, Maharashtra',
//         rating: 4.3,
//         price: 2000,
//         totalPrice: 2400,
//         images: ['assets/cars/polo.avif'],
//         category: 'Cars',
//         isGuestFavorite: false,
//         hasMap: true,
//         distanceDescription: '15 km away',
//         availabilityDescription: 'Available this weekend',
//       ),
    
//       // Bikes (6 items)
//       Property(
//         id: 'bike1',
//         title: 'Royal Enfield Classic 350',
//         location: 'Jaipur, Rajasthan',
//         rating: 4.7,
//         price: 1500,
//         totalPrice: 1800,
//         images: ['assets/bikes/re350.png'],
//         category: 'Bikes',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: '4 km away',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'bike2',
//         title: 'Harley Davidson Iron 883',
//         location: 'Goa, India',
//         rating: 4.9,
//         price: 3000,
//         totalPrice: 3600,
//         images: ['assets/bikes/harley.png'],
//         category: 'Bikes',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: '6 km away',
//         availabilityDescription: 'Available tomorrow',
//       ),
//       Property(
//         id: 'bike3',
//         title: 'KTM Duke 390',
//         location: 'Bangalore, Karnataka',
//         rating: 4.6,
//         price: 1800,
//         totalPrice: 2160,
//         images: ['assets/bikes/ktm.png'],
//         category: 'Bikes',
//         isGuestFavorite: false,
//         hasMap: true,
//         distanceDescription: '9 km away',
//         availabilityDescription: 'Available today',
//       ),
//       Property(
//         id: 'bike4',
//         title: 'Kawasaki Ninja 650',
//         location: 'Mumbai, Maharashtra',
//         rating: 4.8,
//         price: 2500,
//         totalPrice: 3000,
//         images: ['assets/bikes/ninja.png'],
//         category: 'Bikes',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: '11 km away',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'bike5',
//         title: 'Yamaha R15',
//         location: 'Delhi, India',
//         rating: 4.5,
//         price: 1200,
//         totalPrice: 1440,
//         images: ['assets/bikes/r15.png'],
//         category: 'Bikes',
//         isGuestFavorite: false,
//         hasMap: true,
//         distanceDescription: '8 km away',
//         availabilityDescription: 'Available from Monday',
//       ),
//       Property(
//         id: 'bike6',
//         title: 'Bajaj Dominar 400',
//         location: 'Pune, Maharashtra',
//         rating: 4.4,
//         price: 1600,
//         totalPrice: 1920,
//         images: ['assets/bikes/dominar.png'],
//         category: 'Bikes',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: '5 km away',
//         availabilityDescription: 'Available this weekend',
//       ),
    
//       // Laptops (6 items)
//       Property(
//         id: 'laptop1',
//         title: 'MacBook Pro M1',
//         location: 'Mumbai, Maharashtra',
//         rating: 4.9,
//         price: 2500,
//         totalPrice: 3000,
//         images: ['assets/laptops/macbook.png'],
//         category: 'Laptops',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'Central Mumbai',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'laptop2',
//         title: 'Dell XPS 13',
//         location: 'Bangalore, Karnataka',
//         rating: 4.7,
//         price: 2000,
//         totalPrice: 2400,
//         images: ['assets/laptops/xps.png'],
//         category: 'Laptops',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'Koramangala',
//         availabilityDescription: 'Available today',
//       ),
//       Property(
//         id: 'laptop3',
//         title: 'HP Spectre x360',
//         location: 'Delhi, India',
//         rating: 4.6,
//         price: 1800,
//         totalPrice: 2160,
//         images: ['assets/laptops/spectre.png'],
//         category: 'Laptops',
//         isGuestFavorite: false,
//         hasMap: false,
//         distanceDescription: 'South Delhi',
//         availabilityDescription: 'Available tomorrow',
//       ),
//       Property(
//         id: 'laptop4',
//         title: 'Lenovo ThinkPad X1',
//         location: 'Hyderabad, Telangana',
//         rating: 4.5,
//         price: 1900,
//         totalPrice: 2280,
//         images: ['assets/laptops/thinkpad.png'],
//         category: 'Laptops',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'Hitec City',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'laptop5',
//         title: 'Asus ROG Zephyrus',
//         location: 'Chennai, Tamil Nadu',
//         rating: 4.8,
//         price: 2200,
//         totalPrice: 2640,
//         images: ['assets/laptops/rog.png'],
//         category: 'Laptops',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'T Nagar',
//         availabilityDescription: 'Available today',
//       ),
//       Property(
//         id: 'laptop6',
//         title: 'Acer Predator',
//         location: 'Pune, Maharashtra',
//         rating: 4.4,
//         price: 1700,
//         totalPrice: 2040,
//         images: ['assets/laptops/predator.png'],
//         category: 'Laptops',
//         isGuestFavorite: false,
//         hasMap: false,
//         distanceDescription: 'Kothrud',
//         availabilityDescription: 'Available from Monday',
//       ),
    
//       // Cameras (6 items)
//       Property(
//         id: 'camera1',
//         title: 'Canon EOS R5',
//         location: 'Mumbai, Maharashtra',
//         rating: 4.9,
//         price: 3000,
//         totalPrice: 3600,
//         images: ['assets/cameras/r5.png'],
//         category: 'Cameras',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'Andheri',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'camera2',
//         title: 'Sony A7 III',
//         location: 'Delhi, India',
//         rating: 4.8,
//         price: 2800,
//         totalPrice: 3360,
//         images: ['assets/cameras/a7iii.png'],
//         category: 'Cameras',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'Connaught Place',
//         availabilityDescription: 'Available today',
//       ),
//       Property(
//         id: 'camera3',
//         title: 'Nikon Z6',
//         location: 'Bangalore, Karnataka',
//         rating: 4.7,
//         price: 2500,
//         totalPrice: 3000,
//         images: ['assets/cameras/z6.png'],
//         category: 'Cameras',
//         isGuestFavorite: false,
//         hasMap: false,
//         distanceDescription: 'Indiranagar',
//         availabilityDescription: 'Available tomorrow',
//       ),
//       Property(
//         id: 'camera4',
//         title: 'Fujifilm X-T4',
//         location: 'Chennai, Tamil Nadu',
//         rating: 4.6,
//         price: 2200,
//         totalPrice: 2640,
//         images: ['assets/cameras/xt4.png'],
//         category: 'Cameras',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'Adyar',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'camera5',
//         title: 'Panasonic GH5',
//         location: 'Hyderabad, Telangana',
//         rating: 4.5,
//         price: 2000,
//         totalPrice: 2400,
//         images: ['assets/cameras/gh5.png'],
//         category: 'Cameras',
//         isGuestFavorite: false,
//         hasMap: false,
//         distanceDescription: 'Banjara Hills',
//         availabilityDescription: 'Available today',
//       ),
//       Property(
//         id: 'camera6',
//         title: 'BlackMagic Pocket 6K',
//         location: 'Pune, Maharashtra',
//         rating: 4.8,
//         price: 3500,
//         totalPrice: 4200,
//         images: ['assets/cameras/blackmagic.png'],
//         category: 'Cameras',
//         isGuestFavorite: true,
//         hasMap: false,
//         distanceDescription: 'Kalyani Nagar',
//         availabilityDescription: 'Available this weekend',
//       ),
    
//       // Houses (6 items)
//       Property(
//         id: 'house1',
//         title: 'Luxury Villa with Pool',
//         location: 'Lonavala, Maharashtra',
//         rating: 4.9,
//         price: 15000,
//         totalPrice: 18000,
//         images: ['assets/houses/villa1.png'],
//         category: 'Houses',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: 'Hill Station',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'house2',
//         title: 'Beachfront Cottage',
//         location: 'Goa, India',
//         rating: 4.8,
//         price: 12000,
//         totalPrice: 14400,
//         images: ['assets/houses/cottage.png'],
//         category: 'Houses',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: 'Calangute Beach',
//         availabilityDescription: 'Available this weekend',
//       ),
//       Property(
//         id: 'house3',
//         title: 'Mountain View Cabin',
//         location: 'Manali, Himachal Pradesh',
//         rating: 4.7,
//         price: 8000,
//         totalPrice: 9600,
//         images: ['assets/houses/cabin.png'],
//         category: 'Houses',
//         isGuestFavorite: false,
//         hasMap: true,
//         distanceDescription: 'Near Mall Road',
//         availabilityDescription: 'Available next week',
//       ),
//       Property(
//         id: 'house4',
//         title: 'Modern Apartment',
//         location: 'Mumbai, Maharashtra',
//         rating: 4.6,
//         price: 10000,
//         totalPrice: 12000,
//         images: ['assets/houses/apartment.png'],
//         category: 'Houses',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: 'Bandra West',
//         availabilityDescription: 'Available now',
//       ),
//       Property(
//         id: 'house5',
//         title: 'Heritage Haveli',
//         location: 'Jaipur, Rajasthan',
//         rating: 4.9,
//         price: 20000,
//         totalPrice: 24000,
//         images: ['assets/houses/haveli.png'],
//         category: 'Houses',
//         isGuestFavorite: true,
//         hasMap: true,
//         distanceDescription: 'Old City',
//         availabilityDescription: 'Available today',
//       ),
//     ];